// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 784830557ea2

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized, .enabled(if: ContractSupport.channelTestsEnabled)) struct ApiObjectChannelContractTests {

    @Test func api_object_channel_join_by_id_joins_and_receives_contract_valid_reply() async throws {
        try await ContractSupport.withHarnessSocket { _, socket in
            let channel = try await ApiObjectChannel.joinById(socket: socket, objectId: "test-id", connectionId: "test-id", partialUpdates: true)
            #expect(channel.joinResponse != nil)
        }
    }

    @Test func api_object_channel_join_by_id_surfaces_server_error_reply_as_channel_error() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:object:test-id",
                "onJoin": [["type": "replyError", "payload": ["reason": "test_error"]]],
            ])
            await #expect(throws: ChannelError.self) {
                _ = try await ApiObjectChannel.joinById(socket: socket, objectId: "test-id", connectionId: "test-id", partialUpdates: true)
            }
        }
    }

    @Test func api_object_channel_join_by_row_key_joins_and_receives_contract_valid_reply() async throws {
        try await ContractSupport.withHarnessSocket { _, socket in
            let channel = try await ApiObjectChannel.joinByRowKey(socket: socket, schemaType: "test-value", rowKey: "test-key", connectionId: "test-id", partialUpdates: true)
            #expect(channel.joinResponse != nil)
        }
    }

    @Test func api_object_channel_join_by_row_key_surfaces_server_error_reply_as_channel_error() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:object:test-value:test-key",
                "onJoin": [["type": "replyError", "payload": ["reason": "test_error"]]],
            ])
            await #expect(throws: ChannelError.self) {
                _ = try await ApiObjectChannel.joinByRowKey(socket: socket, schemaType: "test-value", rowKey: "test-key", connectionId: "test-id", partialUpdates: true)
            }
        }
    }

    @Test func api_object_channel_update_fields_sends_valid_push_and_receives_contract_valid_reply() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:object:test-id",
                "onJoin": [["type": "autoReply"]],
                "onMessage": ["update_fields": [["type": "autoReply"]]],
            ])
            let channel = try await ApiObjectChannel.joinById(socket: socket, objectId: "test-id", connectionId: "test-id", partialUpdates: true)
            let reply = try await channel.updateFields(payload: ApiObjectUpdateFieldsInput(fields: [:], operationId: "test-id"))
            #expect(reply.status == "ok")

            let observed = try await harness.observations(topic: "api:object:test-id", event: "update_fields")
            #expect(observed.count == 1)
            #expect(observed.first?["params"]?["fields"] == [:])
        }
    }

    @Test func api_object_channel_update_fields_returns_error_envelope_when_required_missing() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:object:test-id",
                "onJoin": [["type": "autoReply"]],
            ])
            let channel = try await ApiObjectChannel.joinById(socket: socket, objectId: "test-id", connectionId: "test-id", partialUpdates: true)
            // Raw push bypasses the typed payload struct.
            let reply = try await channel.channel.push("update_fields", payload: [:] as [String: JSONValue])
            #expect(reply.status == "error")
        }
    }

    @Test func api_object_channel_save_sends_valid_push_and_receives_contract_valid_reply() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:object:test-id",
                "onJoin": [["type": "autoReply"]],
                "onMessage": ["save": [["type": "autoReply"]]],
            ])
            let channel = try await ApiObjectChannel.joinById(socket: socket, objectId: "test-id", connectionId: "test-id", partialUpdates: true)
            let reply = try await channel.save(payload: [:])
            #expect(reply.status == "ok")

            let observed = try await harness.observations(topic: "api:object:test-id", event: "save")
            #expect(observed.count == 1)
            #expect(observed.first?["params"] != nil)
        }
    }

    @Test func api_object_channel_presence_update_sends_valid_push_and_receives_contract_valid_reply() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:object:test-id",
                "onJoin": [["type": "autoReply"]],
                "onMessage": ["presence_update": [["type": "autoReply"]]],
            ])
            let channel = try await ApiObjectChannel.joinById(socket: socket, objectId: "test-id", connectionId: "test-id", partialUpdates: true)
            let reply = try await channel.presenceUpdate(payload: ApiObjectPresenceUpdateInput(presence: [:]))
            #expect(reply.status == "ok")

            let observed = try await harness.observations(topic: "api:object:test-id", event: "presence_update")
            #expect(observed.count == 1)
            #expect(observed.first?["params"]?["presence"] == [:])
        }
    }

    @Test func api_object_channel_presence_update_returns_error_envelope_when_required_missing() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:object:test-id",
                "onJoin": [["type": "autoReply"]],
            ])
            let channel = try await ApiObjectChannel.joinById(socket: socket, objectId: "test-id", connectionId: "test-id", partialUpdates: true)
            // Raw push bypasses the typed payload struct.
            let reply = try await channel.channel.push("presence_update", payload: [:] as [String: JSONValue])
            #expect(reply.status == "error")
        }
    }

    @Test func api_object_channel_on_object_updated_delivers_contract_valid_payloads() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:object:test-id",
                "onJoin": [
                    ["type": "autoReply"],
                    ["type": "autoPush", "event": "object_updated"],
                ],
            ])
            let channel = try await ApiObjectChannel.joinById(socket: socket, objectId: "test-id", connectionId: "test-id", partialUpdates: true)
            let payload = try await ContractSupport.awaitFirst { yield in
                channel.onObjectUpdated { payload in yield(payload) }
            }
            ContractSupport.use(payload)
        }
    }

    @Test func api_object_channel_on_object_created_delivers_contract_valid_payloads() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:object:test-id",
                "onJoin": [
                    ["type": "autoReply"],
                    ["type": "autoPush", "event": "object_created"],
                ],
            ])
            let channel = try await ApiObjectChannel.joinById(socket: socket, objectId: "test-id", connectionId: "test-id", partialUpdates: true)
            let payload = try await ContractSupport.awaitFirst { yield in
                channel.onObjectCreated { payload in yield(payload) }
            }
            ContractSupport.use(payload)
        }
    }

    @Test func api_object_channel_on_object_deleted_delivers_contract_valid_payloads() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:object:test-id",
                "onJoin": [
                    ["type": "autoReply"],
                    ["type": "autoPush", "event": "object_deleted"],
                ],
            ])
            let channel = try await ApiObjectChannel.joinById(socket: socket, objectId: "test-id", connectionId: "test-id", partialUpdates: true)
            let payload = try await ContractSupport.awaitFirst { yield in
                channel.onObjectDeleted { payload in yield(payload) }
            }
            ContractSupport.use(payload)
        }
    }

    @Test func api_object_channel_on_presence_updated_delivers_contract_valid_payloads() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:object:test-id",
                "onJoin": [
                    ["type": "autoReply"],
                    ["type": "autoPush", "event": "presence_updated"],
                ],
            ])
            let channel = try await ApiObjectChannel.joinById(socket: socket, objectId: "test-id", connectionId: "test-id", partialUpdates: true)
            let payload = try await ContractSupport.awaitFirst { yield in
                channel.onPresenceUpdated { payload in yield(payload) }
            }
            ContractSupport.use(payload)
        }
    }

    @Test func api_object_channel_on_presence_left_delivers_contract_valid_payloads() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:object:test-id",
                "onJoin": [
                    ["type": "autoReply"],
                    ["type": "autoPush", "event": "presence_left"],
                ],
            ])
            let channel = try await ApiObjectChannel.joinById(socket: socket, objectId: "test-id", connectionId: "test-id", partialUpdates: true)
            let payload = try await ContractSupport.awaitFirst { yield in
                channel.onPresenceLeft { payload in yield(payload) }
            }
            ContractSupport.use(payload)
        }
    }

    @Test func api_object_channel_on_access_revoked_delivers_contract_valid_payloads() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:object:test-id",
                "onJoin": [
                    ["type": "autoReply"],
                    ["type": "autoPush", "event": "access_revoked"],
                ],
            ])
            let channel = try await ApiObjectChannel.joinById(socket: socket, objectId: "test-id", connectionId: "test-id", partialUpdates: true)
            let payload = try await ContractSupport.awaitFirst { yield in
                channel.onAccessRevoked { payload in yield(payload) }
            }
            ContractSupport.use(payload)
        }
    }

    @Test func api_object_channel_leave_leaves_cleanly_through_generated_leave() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:object:test-id",
                "onJoin": [["type": "autoReply"]],
            ])
            let channel = try await ApiObjectChannel.joinById(socket: socket, objectId: "test-id", connectionId: "test-id", partialUpdates: true)
            try await channel.leave()
        }
    }
}
