// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 7b1817ed8c2b

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized, .enabled(if: ContractSupport.channelTestsEnabled)) struct ApiTasksChannelContractTests {

    @Test func api_tasks_channel_join_thread_joins_and_receives_contract_valid_reply() async throws {
        try await ContractSupport.withHarnessSocket { _, socket in
            let channel = try await ApiTasksChannel.joinThread(socket: socket, threadId: "test-id")
            #expect(channel.joinResponse != nil)
        }
    }

    @Test func api_tasks_channel_join_thread_surfaces_server_error_reply_as_channel_error() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:tasks:thread:test-id",
                "onJoin": [["type": "replyError", "payload": ["reason": "test_error"]]],
            ])
            await #expect(throws: ChannelError.self) {
                _ = try await ApiTasksChannel.joinThread(socket: socket, threadId: "test-id")
            }
        }
    }

    @Test func api_tasks_channel_on_tasks_updated_delivers_contract_valid_payloads() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:tasks:thread:test-id",
                "onJoin": [
                    ["type": "autoReply"],
                    ["type": "autoPush", "event": "tasks_updated"],
                ],
            ])
            let channel = try await ApiTasksChannel.joinThread(socket: socket, threadId: "test-id")
            let payload = try await ContractSupport.awaitFirst { yield in
                channel.onTasksUpdated { payload in yield(payload) }
            }
            ContractSupport.use(payload)
        }
    }

    @Test func api_tasks_channel_leave_leaves_cleanly_through_generated_leave() async throws {
        try await ContractSupport.withHarnessSocket { harness, socket in
            try await harness.registerScenario([
                "topic": "api:tasks:thread:test-id",
                "onJoin": [["type": "autoReply"]],
            ])
            let channel = try await ApiTasksChannel.joinThread(socket: socket, threadId: "test-id")
            try await channel.leave()
        }
    }
}
