// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 65b2f240d6c5

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct ActivityFeedContractTests {

    @Test func activity_feed_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.activityFeed.list()
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func activity_feed_list_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.activityFeed.list()
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func activity_feed_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.activityFeed.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func activity_feed_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.activityFeed.list()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }
}
