// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 9755625e2b84

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct AgentSessionsContractTests {

    @Test func agent_sessions_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentSessions.list()
        ContractSupport.use(result)
    }

    @Test func agent_sessions_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentSessions.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_sessions_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentSessions.list()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_sessions_list_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agentSessions.list()
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agent_sessions_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentSessions.create(input: AgentSessionCreateInput(agent: "test-value", instructions: "test-value"))
        ContractSupport.use(result)
    }

    @Test func agent_sessions_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentSessions.create(input: AgentSessionCreateInput(agent: "test-value", instructions: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_sessions_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentSessions.create(input: AgentSessionCreateInput(agent: "test-value", instructions: "test-value"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_sessions_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentSessions.create(input: AgentSessionCreateInput(agent: "test-value", instructions: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_sessions_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agentSessions.create(input: AgentSessionCreateInput(agent: "test-value", instructions: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agent_sessions_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.agentSessions.delete(agentSession: "test-value")
    }

    @Test func agent_sessions_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.agentSessions.delete(agentSession: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_sessions_delete_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.agentSessions.delete(agentSession: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_sessions_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.agentSessions.delete(agentSession: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_sessions_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentSessions.get(agentSession: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_sessions_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentSessions.get(agentSession: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_sessions_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentSessions.get(agentSession: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_sessions_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentSessions.get(agentSession: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_sessions_update_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentSessions.update(agentSession: "test-value", input: AgentSessionUpdateInput())
        ContractSupport.use(result)
    }

    @Test func agent_sessions_update_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentSessions.update(agentSession: "test-value", input: AgentSessionUpdateInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_sessions_update_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentSessions.update(agentSession: "test-value", input: AgentSessionUpdateInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_sessions_update_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentSessions.update(agentSession: "test-value", input: AgentSessionUpdateInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_sessions_update_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agentSessions.update(agentSession: "test-value", input: AgentSessionUpdateInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agent_sessions_cancel_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentSessions.cancel(agentSession: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_sessions_cancel_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentSessions.cancel(agentSession: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_sessions_cancel_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentSessions.cancel(agentSession: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_sessions_cancel_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentSessions.cancel(agentSession: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_sessions_message_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentSessions.message(agentSession: "test-value", input: AgentSessionMessageInput(content: "test content"))
        ContractSupport.use(result)
    }

    @Test func agent_sessions_message_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentSessions.message(agentSession: "test-value", input: AgentSessionMessageInput(content: "test content"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_sessions_message_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentSessions.message(agentSession: "test-value", input: AgentSessionMessageInput(content: "test content"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_sessions_message_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentSessions.message(agentSession: "test-value", input: AgentSessionMessageInput(content: "test content"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_sessions_message_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agentSessions.message(agentSession: "test-value", input: AgentSessionMessageInput(content: "test content"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }
}
