// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 4babcc9fa29d

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct AgentSkillsContractTests {

    @Test func agent_skills_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentSkills.list()
        ContractSupport.use(result)
    }

    @Test func agent_skills_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentSkills.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_skills_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentSkills.list()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_skills_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentSkills.list()
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_skills_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentSkills.create(input: AgentSkillCreateInput(agent: "test-value", config: "test-value"))
        ContractSupport.use(result)
    }

    @Test func agent_skills_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentSkills.create(input: AgentSkillCreateInput(agent: "test-value", config: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_skills_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentSkills.create(input: AgentSkillCreateInput(agent: "test-value", config: "test-value"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_skills_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentSkills.create(input: AgentSkillCreateInput(agent: "test-value", config: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_skills_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agentSkills.create(input: AgentSkillCreateInput(agent: "test-value", config: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agent_skills_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.agentSkills.delete(agentSkill: "test-value")
    }

    @Test func agent_skills_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.agentSkills.delete(agentSkill: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_skills_delete_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.agentSkills.delete(agentSkill: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_skills_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.agentSkills.delete(agentSkill: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_skills_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentSkills.get(agentSkill: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_skills_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentSkills.get(agentSkill: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_skills_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentSkills.get(agentSkill: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_skills_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentSkills.get(agentSkill: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_skills_update_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentSkills.update(agentSkill: "test-value", input: AgentSkillUpdateInput())
        ContractSupport.use(result)
    }

    @Test func agent_skills_update_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentSkills.update(agentSkill: "test-value", input: AgentSkillUpdateInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_skills_update_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentSkills.update(agentSkill: "test-value", input: AgentSkillUpdateInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_skills_update_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentSkills.update(agentSkill: "test-value", input: AgentSkillUpdateInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_skills_update_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agentSkills.update(agentSkill: "test-value", input: AgentSkillUpdateInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agent_skills_activate_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentSkills.activate(agentSkill: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_skills_activate_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentSkills.activate(agentSkill: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_skills_activate_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentSkills.activate(agentSkill: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_skills_activate_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentSkills.activate(agentSkill: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_skills_deactivate_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentSkills.deactivate(agentSkill: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_skills_deactivate_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentSkills.deactivate(agentSkill: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_skills_deactivate_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentSkills.deactivate(agentSkill: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_skills_deactivate_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentSkills.deactivate(agentSkill: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }
}
