// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: bd79128e12e5

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct AgentRoutinesContractTests {

    @Test func agent_routines_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentRoutines.list()
        ContractSupport.use(result)
    }

    @Test func agent_routines_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentRoutines.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_routines_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentRoutines.list()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_routines_presets_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentRoutines.presets()
        #expect(result.count >= 0)
    }

    @Test func agent_routines_presets_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentRoutines.presets()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_routines_presets_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentRoutines.presets()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_routines_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.agentRoutines.delete(routine: "test-value")
    }

    @Test func agent_routines_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.agentRoutines.delete(routine: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_routines_delete_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.agentRoutines.delete(routine: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_routines_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.agentRoutines.delete(routine: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_routines_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentRoutines.get(routine: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_routines_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentRoutines.get(routine: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_routines_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentRoutines.get(routine: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_routines_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentRoutines.get(routine: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_routines_update_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentRoutines.update(routine: "test-value", input: AgentRoutineUpdateInput())
        ContractSupport.use(result)
    }

    @Test func agent_routines_update_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentRoutines.update(routine: "test-value", input: AgentRoutineUpdateInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_routines_update_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentRoutines.update(routine: "test-value", input: AgentRoutineUpdateInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_routines_update_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentRoutines.update(routine: "test-value", input: AgentRoutineUpdateInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_routines_update_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agentRoutines.update(routine: "test-value", input: AgentRoutineUpdateInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agent_routines_activate_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentRoutines.activate(routine: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_routines_activate_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentRoutines.activate(routine: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_routines_activate_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentRoutines.activate(routine: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_routines_activate_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentRoutines.activate(routine: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_routines_activate_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agentRoutines.activate(routine: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agent_routines_invoke_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentRoutines.invoke(routine: "test-value", input: AgentRoutineInvokeInput(message: "test-value"))
        ContractSupport.use(result)
    }

    @Test func agent_routines_invoke_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.agentRoutines.invoke(routine: "test-value", input: AgentRoutineInvokeInput(message: "test-value"))
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func agent_routines_invoke_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentRoutines.invoke(routine: "test-value", input: AgentRoutineInvokeInput(message: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_routines_invoke_error_402() async throws {
        let client = try await ContractSupport.errorClient(402)
        do {
            _ = try await client.v1.agentRoutines.invoke(routine: "test-value", input: AgentRoutineInvokeInput(message: "test-value"))
            Issue.record("Expected ApiError with status 402")
        }
        catch let error as ApiError {
            #expect(error.status == 402)
        }
    }

    @Test func agent_routines_invoke_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentRoutines.invoke(routine: "test-value", input: AgentRoutineInvokeInput(message: "test-value"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_routines_invoke_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentRoutines.invoke(routine: "test-value", input: AgentRoutineInvokeInput(message: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_routines_invoke_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agentRoutines.invoke(routine: "test-value", input: AgentRoutineInvokeInput(message: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agent_routines_pause_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentRoutines.pause(routine: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_routines_pause_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentRoutines.pause(routine: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_routines_pause_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentRoutines.pause(routine: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_routines_pause_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentRoutines.pause(routine: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_routines_runs_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentRoutines.runs(routine: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_routines_runs_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.agentRoutines.runs(routine: "test-value")
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func agent_routines_runs_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentRoutines.runs(routine: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_routines_runs_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentRoutines.runs(routine: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_routines_runs_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentRoutines.runs(routine: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_routines_agent_routine_runs_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentRoutines.agentRoutineRuns.get(run: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_routines_agent_routine_runs_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentRoutines.agentRoutineRuns.get(run: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_routines_agent_routine_runs_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentRoutines.agentRoutineRuns.get(run: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_routines_agent_routine_runs_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentRoutines.agentRoutineRuns.get(run: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }
}
