// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: f1797e280233

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct AgentInstallationsContractTests {

    @Test func agent_installations_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentInstallations.list()
        ContractSupport.use(result)
    }

    @Test func agent_installations_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentInstallations.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_installations_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentInstallations.list()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_installations_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.agentInstallations.delete(installation: "test-value")
    }

    @Test func agent_installations_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.agentInstallations.delete(installation: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_installations_delete_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.agentInstallations.delete(installation: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_installations_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.agentInstallations.delete(installation: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_installations_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentInstallations.get(installation: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_installations_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentInstallations.get(installation: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_installations_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentInstallations.get(installation: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_installations_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentInstallations.get(installation: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_installations_activate_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentInstallations.activate(installation: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_installations_activate_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentInstallations.activate(installation: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_installations_activate_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentInstallations.activate(installation: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_installations_activate_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentInstallations.activate(installation: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_installations_activate_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agentInstallations.activate(installation: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agent_installations_pause_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentInstallations.pause(installation: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_installations_pause_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentInstallations.pause(installation: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_installations_pause_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentInstallations.pause(installation: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_installations_pause_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentInstallations.pause(installation: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_installations_pause_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agentInstallations.pause(installation: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agent_installations_suspend_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentInstallations.suspend(installation: "test-value", input: AgentInstallationSuspendInput())
        ContractSupport.use(result)
    }

    @Test func agent_installations_suspend_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentInstallations.suspend(installation: "test-value", input: AgentInstallationSuspendInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_installations_suspend_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentInstallations.suspend(installation: "test-value", input: AgentInstallationSuspendInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_installations_suspend_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentInstallations.suspend(installation: "test-value", input: AgentInstallationSuspendInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_installations_suspend_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agentInstallations.suspend(installation: "test-value", input: AgentInstallationSuspendInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agent_installations_installation_sources_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentInstallations.installationSources.list(installation: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_installations_installation_sources_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentInstallations.installationSources.list(installation: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_installations_installation_sources_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentInstallations.installationSources.list(installation: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_installations_installation_sources_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentInstallations.installationSources.list(installation: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_installations_installation_sources_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentInstallations.installationSources.create(installation: "test-value", input: AgentInstallationInstallationSourceCreateInput(payload: [:], type: "test"))
        ContractSupport.use(result)
    }

    @Test func agent_installations_installation_sources_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentInstallations.installationSources.create(installation: "test-value", input: AgentInstallationInstallationSourceCreateInput(payload: [:], type: "test"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_installations_installation_sources_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentInstallations.installationSources.create(installation: "test-value", input: AgentInstallationInstallationSourceCreateInput(payload: [:], type: "test"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_installations_installation_sources_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentInstallations.installationSources.create(installation: "test-value", input: AgentInstallationInstallationSourceCreateInput(payload: [:], type: "test"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_installations_installation_sources_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agentInstallations.installationSources.create(installation: "test-value", input: AgentInstallationInstallationSourceCreateInput(payload: [:], type: "test"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }
}
