// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 269f8297fc68

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct AgentsContractTests {

    @Test func agents_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.list()
        ContractSupport.use(result)
    }

    @Test func agents_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.list()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.create(input: AgentCreateInput())
        ContractSupport.use(result)
    }

    @Test func agents_create_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.agents.create(input: AgentCreateInput())
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func agents_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.create(input: AgentCreateInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.create(input: AgentCreateInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.create(input: AgentCreateInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_create_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.agents.create(input: AgentCreateInput())
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func agents_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agents.create(input: AgentCreateInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agents_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.agents.delete(agent: "test-value")
    }

    @Test func agents_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.agents.delete(agent: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_delete_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.agents.delete(agent: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.agents.delete(agent: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.get(agent: "test-value")
        ContractSupport.use(result)
    }

    @Test func agents_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.get(agent: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.get(agent: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.get(agent: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_update_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.update(agent: "test-value", input: AgentUpdateInput())
        ContractSupport.use(result)
    }

    @Test func agents_update_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.update(agent: "test-value", input: AgentUpdateInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_update_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.update(agent: "test-value", input: AgentUpdateInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_update_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.update(agent: "test-value", input: AgentUpdateInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_update_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agents.update(agent: "test-value", input: AgentUpdateInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agents_agent_health_actions_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.agentHealthActions(agent: "test-value")
        ContractSupport.use(result)
    }

    @Test func agents_agent_health_actions_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.agentHealthActions(agent: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_agent_health_actions_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.agentHealthActions(agent: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_agent_health_actions_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.agentHealthActions(agent: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_agent_routines_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.agentRoutines(agent: "test-value", input: AgentAgentRoutinesInput(handlerType: "test-value", name: "test-name"))
        ContractSupport.use(result)
    }

    @Test func agents_agent_routines_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.agentRoutines(agent: "test-value", input: AgentAgentRoutinesInput(handlerType: "test-value", name: "test-name"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_agent_routines_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.agentRoutines(agent: "test-value", input: AgentAgentRoutinesInput(handlerType: "test-value", name: "test-name"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_agent_routines_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.agentRoutines(agent: "test-value", input: AgentAgentRoutinesInput(handlerType: "test-value", name: "test-name"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_agent_routines_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agents.agentRoutines(agent: "test-value", input: AgentAgentRoutinesInput(handlerType: "test-value", name: "test-name"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agents_agent_working_memory_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.agentWorkingMemory(agent: "test-value")
        ContractSupport.use(result)
    }

    @Test func agents_agent_working_memory_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.agentWorkingMemory(agent: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_agent_working_memory_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.agentWorkingMemory(agent: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_agent_working_memory_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.agentWorkingMemory(agent: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_export_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.export(agent: "test-value")
        ContractSupport.use(result)
    }

    @Test func agents_export_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.export(agent: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_export_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.export(agent: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_export_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.export(agent: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_health_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.health(agent: "test-value")
        ContractSupport.use(result)
    }

    @Test func agents_health_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.health(agent: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_health_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.health(agent: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_health_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.health(agent: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_search_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.search(agent: "test-value", input: AgentSearchInput(query: "test-value"))
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func agents_search_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.search(agent: "test-value", input: AgentSearchInput(query: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_search_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.search(agent: "test-value", input: AgentSearchInput(query: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_search_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agents.search(agent: "test-value", input: AgentSearchInput(query: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agents_threads_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.threads(agent: "test-value", input: AgentThreadsInput(thread: AgentThreadsInputThread()))
        ContractSupport.use(result)
    }

    @Test func agents_threads_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.threads(agent: "test-value", input: AgentThreadsInput(thread: AgentThreadsInputThread()))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_threads_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.threads(agent: "test-value", input: AgentThreadsInput(thread: AgentThreadsInputThread()))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_threads_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.threads(agent: "test-value", input: AgentThreadsInput(thread: AgentThreadsInputThread()))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_threads_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agents.threads(agent: "test-value", input: AgentThreadsInput(thread: AgentThreadsInputThread()))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agents_upgrade_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.upgrade(agent: "test-value", input: AgentUpgradeInput())
        ContractSupport.use(result)
    }

    @Test func agents_upgrade_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.agents.upgrade(agent: "test-value", input: AgentUpgradeInput())
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func agents_upgrade_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.upgrade(agent: "test-value", input: AgentUpgradeInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_upgrade_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.upgrade(agent: "test-value", input: AgentUpgradeInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_upgrade_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.upgrade(agent: "test-value", input: AgentUpgradeInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_upgrade_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.agents.upgrade(agent: "test-value", input: AgentUpgradeInput())
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func agents_upgrade_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agents.upgrade(agent: "test-value", input: AgentUpgradeInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agents_agent_computers_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.agentComputers.list(agent: "test-value")
        ContractSupport.use(result)
    }

    @Test func agents_agent_computers_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.agentComputers.list(agent: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_agent_computers_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.agentComputers.list(agent: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_agent_computers_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.agentComputers.list(agent: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_agent_computers_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.agentComputers.create(agent: "test-value", input: AgentAgentComputerCreateInput(name: "test-name"))
        ContractSupport.use(result)
    }

    @Test func agents_agent_computers_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.agentComputers.create(agent: "test-value", input: AgentAgentComputerCreateInput(name: "test-name"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_agent_computers_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.agentComputers.create(agent: "test-value", input: AgentAgentComputerCreateInput(name: "test-name"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_agent_computers_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.agentComputers.create(agent: "test-value", input: AgentAgentComputerCreateInput(name: "test-name"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_agent_computers_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agents.agentComputers.create(agent: "test-value", input: AgentAgentComputerCreateInput(name: "test-name"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agents_agent_env_vars_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.agentEnvVars.list(agent: "test-value")
        ContractSupport.use(result)
    }

    @Test func agents_agent_env_vars_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.agentEnvVars.list(agent: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_agent_env_vars_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.agentEnvVars.list(agent: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_agent_env_vars_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.agentEnvVars.list(agent: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_agent_env_vars_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.agentEnvVars.create(agent: "test-value", input: AgentAgentEnvVarCreateInput(key: "test-key", value: "test-value"))
        ContractSupport.use(result)
    }

    @Test func agents_agent_env_vars_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.agentEnvVars.create(agent: "test-value", input: AgentAgentEnvVarCreateInput(key: "test-key", value: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_agent_env_vars_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.agentEnvVars.create(agent: "test-value", input: AgentAgentEnvVarCreateInput(key: "test-key", value: "test-value"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_agent_env_vars_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.agentEnvVars.create(agent: "test-value", input: AgentAgentEnvVarCreateInput(key: "test-key", value: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_agent_env_vars_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agents.agentEnvVars.create(agent: "test-value", input: AgentAgentEnvVarCreateInput(key: "test-key", value: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agents_agent_installations_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.agentInstallations.list(agent: "test-value")
        ContractSupport.use(result)
    }

    @Test func agents_agent_installations_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.agentInstallations.list(agent: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_agent_installations_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.agentInstallations.list(agent: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_agent_installations_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.agentInstallations.list(agent: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_agent_installations_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.agentInstallations.create(agent: "test-value", input: AgentAgentInstallationCreateInput(kind: "test"))
        ContractSupport.use(result)
    }

    @Test func agents_agent_installations_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.agentInstallations.create(agent: "test-value", input: AgentAgentInstallationCreateInput(kind: "test"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_agent_installations_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.agentInstallations.create(agent: "test-value", input: AgentAgentInstallationCreateInput(kind: "test"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_agent_installations_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.agentInstallations.create(agent: "test-value", input: AgentAgentInstallationCreateInput(kind: "test"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_agent_installations_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agents.agentInstallations.create(agent: "test-value", input: AgentAgentInstallationCreateInput(kind: "test"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agents_agent_installations_kinds_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.agentInstallations.kinds(agent: "test-value")
        ContractSupport.use(result)
    }

    @Test func agents_agent_installations_kinds_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.agentInstallations.kinds(agent: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_agent_installations_kinds_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.agentInstallations.kinds(agent: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_agent_tools_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.agentTools.list(agent: "test-value")
        ContractSupport.use(result)
    }

    @Test func agents_agent_tools_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.agentTools.list(agent: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_agent_tools_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.agentTools.list(agent: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_agent_tools_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.agentTools.list(agent: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_agent_tools_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.agentTools.create(agent: "test-value", input: AgentAgentToolCreateInput(kind: "test"))
        ContractSupport.use(result)
    }

    @Test func agents_agent_tools_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.agentTools.create(agent: "test-value", input: AgentAgentToolCreateInput(kind: "test"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_agent_tools_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.agentTools.create(agent: "test-value", input: AgentAgentToolCreateInput(kind: "test"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_agent_tools_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.agentTools.create(agent: "test-value", input: AgentAgentToolCreateInput(kind: "test"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agents_agent_tools_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agents.agentTools.create(agent: "test-value", input: AgentAgentToolCreateInput(kind: "test"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func agents_schedules_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.schedules.list(agent: "test-value")
        ContractSupport.use(result)
    }

    @Test func agents_schedules_list_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.agents.schedules.list(agent: "test-value")
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func agents_schedules_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.schedules.list(agent: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_schedules_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.schedules.list(agent: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_schedules_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agents.schedules.get(agent: "test-value", schedule: "test-value")
        ContractSupport.use(result)
    }

    @Test func agents_schedules_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agents.schedules.get(agent: "test-value", schedule: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agents_schedules_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agents.schedules.get(agent: "test-value", schedule: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agents_schedules_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agents.schedules.get(agent: "test-value", schedule: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }
}
