// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 3b6fe4e438ea

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct AgentEnvVarsContractTests {

    @Test func agent_env_vars_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.agentEnvVars.delete(envVar: "test-value")
    }

    @Test func agent_env_vars_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.agentEnvVars.delete(envVar: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_env_vars_delete_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.agentEnvVars.delete(envVar: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_env_vars_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.agentEnvVars.delete(envVar: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_env_vars_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentEnvVars.get(envVar: "test-value")
        ContractSupport.use(result)
    }

    @Test func agent_env_vars_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentEnvVars.get(envVar: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_env_vars_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentEnvVars.get(envVar: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_env_vars_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentEnvVars.get(envVar: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_env_vars_update_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.agentEnvVars.update(envVar: "test-value", input: AgentEnvVarUpdateInput())
        ContractSupport.use(result)
    }

    @Test func agent_env_vars_update_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.agentEnvVars.update(envVar: "test-value", input: AgentEnvVarUpdateInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func agent_env_vars_update_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.agentEnvVars.update(envVar: "test-value", input: AgentEnvVarUpdateInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func agent_env_vars_update_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.agentEnvVars.update(envVar: "test-value", input: AgentEnvVarUpdateInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func agent_env_vars_update_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.agentEnvVars.update(envVar: "test-value", input: AgentEnvVarUpdateInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }
}
