// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 3b151a4059ab

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct AiContractTests {

    @Test func ai_session_token_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.ai.sessionToken(input: AiSessionTokenInput(userId: "test-id"))
        ContractSupport.use(result)
    }

    @Test func ai_session_token_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.ai.sessionToken(input: AiSessionTokenInput(userId: "test-id"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func ai_session_token_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.ai.sessionToken(input: AiSessionTokenInput(userId: "test-id"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func ai_session_token_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.ai.sessionToken(input: AiSessionTokenInput(userId: "test-id"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func ai_chat_models_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.ai.chat.models()
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func ai_chat_models_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.ai.chat.models()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func ai_chat_models_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.ai.chat.models()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func ai_chat_completions_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.ai.chat.completions.create(input: CompletionCreateInput(messages: [CompletionCreateInputMessagesItem(role: "user")], opts: CompletionCreateInputOpts(model: "test-model")))
        ContractSupport.use(result)
    }

    @Test func ai_chat_completions_create_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.ai.chat.completions.create(input: CompletionCreateInput(messages: [CompletionCreateInputMessagesItem(role: "user")], opts: CompletionCreateInputOpts(model: "test-model")))
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func ai_chat_completions_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.ai.chat.completions.create(input: CompletionCreateInput(messages: [CompletionCreateInputMessagesItem(role: "user")], opts: CompletionCreateInputOpts(model: "test-model")))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func ai_chat_completions_create_error_402() async throws {
        let client = try await ContractSupport.errorClient(402)
        do {
            _ = try await client.v1.ai.chat.completions.create(input: CompletionCreateInput(messages: [CompletionCreateInputMessagesItem(role: "user")], opts: CompletionCreateInputOpts(model: "test-model")))
            Issue.record("Expected ApiError with status 402")
        }
        catch let error as ApiError {
            #expect(error.status == 402)
        }
    }

    @Test func ai_chat_completions_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.ai.chat.completions.create(input: CompletionCreateInput(messages: [CompletionCreateInputMessagesItem(role: "user")], opts: CompletionCreateInputOpts(model: "test-model")))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func ai_chat_completions_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.ai.chat.completions.create(input: CompletionCreateInput(messages: [CompletionCreateInputMessagesItem(role: "user")], opts: CompletionCreateInputOpts(model: "test-model")))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func ai_embedding_similarity_comparison_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.ai.embedding.similarityComparison(input: EmbeddingSimilarityComparisonInput(textA: "test-value", textB: "test-value"))
        ContractSupport.use(result)
    }

    @Test func ai_embedding_similarity_comparison_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.ai.embedding.similarityComparison(input: EmbeddingSimilarityComparisonInput(textA: "test-value", textB: "test-value"))
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func ai_embedding_similarity_comparison_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.ai.embedding.similarityComparison(input: EmbeddingSimilarityComparisonInput(textA: "test-value", textB: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func ai_embedding_similarity_comparison_error_402() async throws {
        let client = try await ContractSupport.errorClient(402)
        do {
            _ = try await client.v1.ai.embedding.similarityComparison(input: EmbeddingSimilarityComparisonInput(textA: "test-value", textB: "test-value"))
            Issue.record("Expected ApiError with status 402")
        }
        catch let error as ApiError {
            #expect(error.status == 402)
        }
    }

    @Test func ai_embedding_similarity_comparison_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.ai.embedding.similarityComparison(input: EmbeddingSimilarityComparisonInput(textA: "test-value", textB: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func ai_evaluation_evaluations_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.ai.evaluation.evaluations(input: EvaluationEvaluationsInput(questions: [["id": "test-id", "instructions": "test-value", "type": "boolean"]], state: [:]))
        ContractSupport.use(result)
    }

    @Test func ai_evaluation_evaluations_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.ai.evaluation.evaluations(input: EvaluationEvaluationsInput(questions: [["id": "test-id", "instructions": "test-value", "type": "boolean"]], state: [:]))
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func ai_evaluation_evaluations_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.ai.evaluation.evaluations(input: EvaluationEvaluationsInput(questions: [["id": "test-id", "instructions": "test-value", "type": "boolean"]], state: [:]))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func ai_evaluation_evaluations_error_402() async throws {
        let client = try await ContractSupport.errorClient(402)
        do {
            _ = try await client.v1.ai.evaluation.evaluations(input: EvaluationEvaluationsInput(questions: [["id": "test-id", "instructions": "test-value", "type": "boolean"]], state: [:]))
            Issue.record("Expected ApiError with status 402")
        }
        catch let error as ApiError {
            #expect(error.status == 402)
        }
    }

    @Test func ai_evaluation_evaluations_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.ai.evaluation.evaluations(input: EvaluationEvaluationsInput(questions: [["id": "test-id", "instructions": "test-value", "type": "boolean"]], state: [:]))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func ai_evaluation_evaluations_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.ai.evaluation.evaluations(input: EvaluationEvaluationsInput(questions: [["id": "test-id", "instructions": "test-value", "type": "boolean"]], state: [:]))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func ai_evaluation_models_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.ai.evaluation.models()
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func ai_evaluation_models_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.ai.evaluation.models()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func ai_evaluation_models_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.ai.evaluation.models()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func ai_image_edits_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.ai.image.edits(input: ImageEditsInput(images: [ImageEditsInputImagesItem(imageData: "test-value", imageType: "test-value")], prompt: "test-value"))
        ContractSupport.use(result)
    }

    @Test func ai_image_edits_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.ai.image.edits(input: ImageEditsInput(images: [ImageEditsInputImagesItem(imageData: "test-value", imageType: "test-value")], prompt: "test-value"))
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func ai_image_edits_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.ai.image.edits(input: ImageEditsInput(images: [ImageEditsInputImagesItem(imageData: "test-value", imageType: "test-value")], prompt: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func ai_image_edits_error_402() async throws {
        let client = try await ContractSupport.errorClient(402)
        do {
            _ = try await client.v1.ai.image.edits(input: ImageEditsInput(images: [ImageEditsInputImagesItem(imageData: "test-value", imageType: "test-value")], prompt: "test-value"))
            Issue.record("Expected ApiError with status 402")
        }
        catch let error as ApiError {
            #expect(error.status == 402)
        }
    }

    @Test func ai_image_edits_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.ai.image.edits(input: ImageEditsInput(images: [ImageEditsInputImagesItem(imageData: "test-value", imageType: "test-value")], prompt: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func ai_image_generations_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.ai.image.generations(input: ImageGenerationsInput(prompt: "test-value"))
        ContractSupport.use(result)
    }

    @Test func ai_image_generations_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.ai.image.generations(input: ImageGenerationsInput(prompt: "test-value"))
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func ai_image_generations_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.ai.image.generations(input: ImageGenerationsInput(prompt: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func ai_image_generations_error_402() async throws {
        let client = try await ContractSupport.errorClient(402)
        do {
            _ = try await client.v1.ai.image.generations(input: ImageGenerationsInput(prompt: "test-value"))
            Issue.record("Expected ApiError with status 402")
        }
        catch let error as ApiError {
            #expect(error.status == 402)
        }
    }

    @Test func ai_image_generations_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.ai.image.generations(input: ImageGenerationsInput(prompt: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func ai_image_models_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.ai.image.models()
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func ai_image_models_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.ai.image.models()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }
}
