// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: fe23f27fdf04

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct ArtifactsContractTests {

    @Test func artifacts_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.artifacts.create(input: ArtifactCreateInput())
        ContractSupport.use(result)
    }

    @Test func artifacts_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.artifacts.create(input: ArtifactCreateInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func artifacts_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.artifacts.create(input: ArtifactCreateInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func artifacts_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.artifacts.create(input: ArtifactCreateInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func artifacts_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.artifacts.delete(artifact: "test-value")
    }

    @Test func artifacts_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.artifacts.delete(artifact: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func artifacts_delete_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.artifacts.delete(artifact: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func artifacts_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.artifacts.delete(artifact: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func artifacts_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.artifacts.get(artifact: "test-value")
        ContractSupport.use(result)
    }

    @Test func artifacts_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.artifacts.get(artifact: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func artifacts_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.artifacts.get(artifact: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func artifacts_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.artifacts.get(artifact: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func artifacts_replace_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.artifacts.replace(artifact: "test-value", input: ArtifactReplaceInput(fromVersion: 1))
        ContractSupport.use(result)
    }

    @Test func artifacts_replace_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.artifacts.replace(artifact: "test-value", input: ArtifactReplaceInput(fromVersion: 1))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func artifacts_replace_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.artifacts.replace(artifact: "test-value", input: ArtifactReplaceInput(fromVersion: 1))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func artifacts_replace_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.artifacts.replace(artifact: "test-value", input: ArtifactReplaceInput(fromVersion: 1))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func artifacts_replace_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.artifacts.replace(artifact: "test-value", input: ArtifactReplaceInput(fromVersion: 1))
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func artifacts_replace_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.artifacts.replace(artifact: "test-value", input: ArtifactReplaceInput(fromVersion: 1))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func artifacts_archive_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.artifacts.archive(artifact: "test-value")
    }

    @Test func artifacts_archive_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.artifacts.archive(artifact: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func artifacts_archive_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.artifacts.archive(artifact: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func artifacts_archive_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.artifacts.archive(artifact: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func artifacts_content_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.artifacts.content(artifact: "test-value")
        #expect(!result.mimeType.isEmpty)
    }

    @Test func artifacts_content_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.artifacts.content(artifact: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func artifacts_content_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.artifacts.content(artifact: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func artifacts_content_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.artifacts.content(artifact: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func artifacts_content_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.artifacts.content(artifact: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }
}
