// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 46d840fa7386

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct AutomationsContractTests {

    @Test func automations_invoke_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.automations.invoke(automation: "test-value", input: AutomationInvokeInput())
        ContractSupport.use(result)
    }

    @Test func automations_invoke_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.automations.invoke(automation: "test-value", input: AutomationInvokeInput())
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func automations_invoke_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.automations.invoke(automation: "test-value", input: AutomationInvokeInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func automations_invoke_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.automations.invoke(automation: "test-value", input: AutomationInvokeInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func automations_invoke_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.automations.invoke(automation: "test-value", input: AutomationInvokeInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func automations_invoke_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.automations.invoke(automation: "test-value", input: AutomationInvokeInput())
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func automations_invoke_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.automations.invoke(automation: "test-value", input: AutomationInvokeInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }
}
