// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 738d20213c3f

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct BugReportsContractTests {

    @Test func bug_reports_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.bugReports.create(input: BugReportCreateInput(client: "test-value", clientVersion: "test-value", description: "test description"))
        ContractSupport.use(result)
    }

    @Test func bug_reports_create_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.bugReports.create(input: BugReportCreateInput(client: "test-value", clientVersion: "test-value", description: "test description"))
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func bug_reports_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.bugReports.create(input: BugReportCreateInput(client: "test-value", clientVersion: "test-value", description: "test description"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func bug_reports_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.bugReports.create(input: BugReportCreateInput(client: "test-value", clientVersion: "test-value", description: "test description"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func bug_reports_create_error_429() async throws {
        let client = try await ContractSupport.errorClient(429)
        do {
            _ = try await client.v1.bugReports.create(input: BugReportCreateInput(client: "test-value", clientVersion: "test-value", description: "test description"))
            Issue.record("Expected ApiError with status 429")
        }
        catch let error as ApiError {
            #expect(error.status == 429)
        }
    }
}
