// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 7c00784b8abe

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct CustomObjectsContractTests {

    @Test func custom_objects_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.customObjects.list()
        ContractSupport.use(result)
    }

    @Test func custom_objects_list_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.customObjects.list()
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func custom_objects_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.customObjects.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func custom_objects_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.customObjects.list()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func custom_objects_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.customObjects.create(input: CustomObjectCreateInput())
        ContractSupport.use(result)
    }

    @Test func custom_objects_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.customObjects.create(input: CustomObjectCreateInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func custom_objects_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.customObjects.create(input: CustomObjectCreateInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func custom_objects_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.customObjects.create(input: CustomObjectCreateInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func custom_objects_create_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.customObjects.create(input: CustomObjectCreateInput())
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func custom_objects_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.customObjects.create(input: CustomObjectCreateInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func custom_objects_delete_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.customObjects.delete(object: "test-value")
        ContractSupport.use(result)
    }

    @Test func custom_objects_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.customObjects.delete(object: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func custom_objects_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.customObjects.delete(object: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func custom_objects_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.customObjects.get(object: "test-value")
        ContractSupport.use(result)
    }

    @Test func custom_objects_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.customObjects.get(object: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func custom_objects_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.customObjects.get(object: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func custom_objects_replace_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.customObjects.replace(object: "test-value", input: CustomObjectReplaceInput())
        ContractSupport.use(result)
    }

    @Test func custom_objects_replace_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.customObjects.replace(object: "test-value", input: CustomObjectReplaceInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func custom_objects_replace_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.customObjects.replace(object: "test-value", input: CustomObjectReplaceInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func custom_objects_replace_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.customObjects.replace(object: "test-value", input: CustomObjectReplaceInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func custom_objects_replace_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.customObjects.replace(object: "test-value", input: CustomObjectReplaceInput())
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func custom_objects_replace_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.customObjects.replace(object: "test-value", input: CustomObjectReplaceInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }
}
