// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 1286c9929e05

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct EventSubscriptionsContractTests {

    @Test func event_subscriptions_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.eventSubscriptions.list()
        ContractSupport.use(result)
    }

    @Test func event_subscriptions_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.eventSubscriptions.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func event_subscriptions_list_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.eventSubscriptions.list()
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func event_subscriptions_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.eventSubscriptions.create(input: EventSubscriptionCreateInput(eventNames: ["test-value"], name: "test-name"))
        ContractSupport.use(result)
    }

    @Test func event_subscriptions_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.eventSubscriptions.create(input: EventSubscriptionCreateInput(eventNames: ["test-value"], name: "test-name"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func event_subscriptions_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.eventSubscriptions.create(input: EventSubscriptionCreateInput(eventNames: ["test-value"], name: "test-name"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func event_subscriptions_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.eventSubscriptions.delete(subscription: "test-value")
    }

    @Test func event_subscriptions_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.eventSubscriptions.delete(subscription: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func event_subscriptions_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.eventSubscriptions.delete(subscription: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func event_subscriptions_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.eventSubscriptions.get(subscription: "test-value")
        ContractSupport.use(result)
    }

    @Test func event_subscriptions_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.eventSubscriptions.get(subscription: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func event_subscriptions_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.eventSubscriptions.get(subscription: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func event_subscriptions_update_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.eventSubscriptions.update(subscription: "test-value", input: EventSubscriptionUpdateInput())
        ContractSupport.use(result)
    }

    @Test func event_subscriptions_update_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.eventSubscriptions.update(subscription: "test-value", input: EventSubscriptionUpdateInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func event_subscriptions_update_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.eventSubscriptions.update(subscription: "test-value", input: EventSubscriptionUpdateInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func event_subscriptions_update_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.eventSubscriptions.update(subscription: "test-value", input: EventSubscriptionUpdateInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func event_subscriptions_claim_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.eventSubscriptions.claim(subscription: "test-value", input: EventSubscriptionClaimInput())
        ContractSupport.use(result)
    }

    @Test func event_subscriptions_claim_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.eventSubscriptions.claim(subscription: "test-value", input: EventSubscriptionClaimInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func event_subscriptions_claim_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.eventSubscriptions.claim(subscription: "test-value", input: EventSubscriptionClaimInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func event_subscriptions_claim_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.eventSubscriptions.claim(subscription: "test-value", input: EventSubscriptionClaimInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func event_subscriptions_head_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.eventSubscriptions.head(subscription: "test-value")
        ContractSupport.use(result)
    }

    @Test func event_subscriptions_head_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.eventSubscriptions.head(subscription: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func event_subscriptions_head_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.eventSubscriptions.head(subscription: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func event_subscriptions_queue_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.eventSubscriptions.queue(subscription: "test-value")
        ContractSupport.use(result)
    }

    @Test func event_subscriptions_queue_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.eventSubscriptions.queue(subscription: "test-value")
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func event_subscriptions_queue_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.eventSubscriptions.queue(subscription: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func event_subscriptions_queue_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.eventSubscriptions.queue(subscription: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }
}
