// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 5a8a14bc16e2

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct EventSubscriptionDeliveriesContractTests {

    @Test func event_subscription_deliveries_acknowledge_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.eventSubscriptionDeliveries.acknowledge(delivery: "test-value", input: EventSubscriptionDeliveryAcknowledgeInput(receiptHandle: "test-value"))
    }

    @Test func event_subscription_deliveries_acknowledge_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.eventSubscriptionDeliveries.acknowledge(delivery: "test-value", input: EventSubscriptionDeliveryAcknowledgeInput(receiptHandle: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func event_subscription_deliveries_acknowledge_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.eventSubscriptionDeliveries.acknowledge(delivery: "test-value", input: EventSubscriptionDeliveryAcknowledgeInput(receiptHandle: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func event_subscription_deliveries_acknowledge_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            try await client.v1.eventSubscriptionDeliveries.acknowledge(delivery: "test-value", input: EventSubscriptionDeliveryAcknowledgeInput(receiptHandle: "test-value"))
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }
}
