// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 6c93a32b9a31

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct ExternalObjectsContractTests {

    @Test func external_objects_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.externalObjects.list()
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func external_objects_list_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.externalObjects.list()
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func external_objects_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.externalObjects.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func external_objects_list_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.externalObjects.list()
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func external_objects_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.externalObjects.create(input: ExternalObjectCreateInput(object: ["name": "test-name", "type": "r2_bucket"], service: "cloudflare"))
        ContractSupport.use(result)
    }

    @Test func external_objects_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.externalObjects.create(input: ExternalObjectCreateInput(object: ["name": "test-name", "type": "r2_bucket"], service: "cloudflare"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func external_objects_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.externalObjects.create(input: ExternalObjectCreateInput(object: ["name": "test-name", "type": "r2_bucket"], service: "cloudflare"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func external_objects_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.externalObjects.create(input: ExternalObjectCreateInput(object: ["name": "test-name", "type": "r2_bucket"], service: "cloudflare"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func external_objects_create_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.externalObjects.create(input: ExternalObjectCreateInput(object: ["name": "test-name", "type": "r2_bucket"], service: "cloudflare"))
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func external_objects_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.externalObjects.create(input: ExternalObjectCreateInput(object: ["name": "test-name", "type": "r2_bucket"], service: "cloudflare"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func external_objects_create_error_502() async throws {
        let client = try await ContractSupport.errorClient(502)
        do {
            _ = try await client.v1.externalObjects.create(input: ExternalObjectCreateInput(object: ["name": "test-name", "type": "r2_bucket"], service: "cloudflare"))
            Issue.record("Expected ApiError with status 502")
        }
        catch let error as ApiError {
            #expect(error.status == 502)
        }
    }

    @Test func external_objects_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.externalObjects.delete(externalObject: "test-value")
    }

    @Test func external_objects_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.externalObjects.delete(externalObject: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func external_objects_delete_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.externalObjects.delete(externalObject: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func external_objects_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.externalObjects.delete(externalObject: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func external_objects_delete_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            try await client.v1.externalObjects.delete(externalObject: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func external_objects_delete_error_502() async throws {
        let client = try await ContractSupport.errorClient(502)
        do {
            try await client.v1.externalObjects.delete(externalObject: "test-value")
            Issue.record("Expected ApiError with status 502")
        }
        catch let error as ApiError {
            #expect(error.status == 502)
        }
    }

    @Test func external_objects_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.externalObjects.get(externalObject: "test-value")
        ContractSupport.use(result)
    }

    @Test func external_objects_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.externalObjects.get(externalObject: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func external_objects_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.externalObjects.get(externalObject: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func external_objects_update_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.externalObjects.update(externalObject: "test-value", input: ExternalObjectUpdateInput(object: ["storage_class": "test-value", "type": "r2_bucket"]))
        ContractSupport.use(result)
    }

    @Test func external_objects_update_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.externalObjects.update(externalObject: "test-value", input: ExternalObjectUpdateInput(object: ["storage_class": "test-value", "type": "r2_bucket"]))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func external_objects_update_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.externalObjects.update(externalObject: "test-value", input: ExternalObjectUpdateInput(object: ["storage_class": "test-value", "type": "r2_bucket"]))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func external_objects_update_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.externalObjects.update(externalObject: "test-value", input: ExternalObjectUpdateInput(object: ["storage_class": "test-value", "type": "r2_bucket"]))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func external_objects_update_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.externalObjects.update(externalObject: "test-value", input: ExternalObjectUpdateInput(object: ["storage_class": "test-value", "type": "r2_bucket"]))
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func external_objects_update_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.externalObjects.update(externalObject: "test-value", input: ExternalObjectUpdateInput(object: ["storage_class": "test-value", "type": "r2_bucket"]))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func external_objects_update_error_502() async throws {
        let client = try await ContractSupport.errorClient(502)
        do {
            _ = try await client.v1.externalObjects.update(externalObject: "test-value", input: ExternalObjectUpdateInput(object: ["storage_class": "test-value", "type": "r2_bucket"]))
            Issue.record("Expected ApiError with status 502")
        }
        catch let error as ApiError {
            #expect(error.status == 502)
        }
    }
}
