// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: e1f1f86db4c3

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct ExternalObjectCapabilitiesContractTests {

    @Test func external_object_capabilities_remove_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.externalObjectCapabilities.remove()
    }

    @Test func external_object_capabilities_remove_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.externalObjectCapabilities.remove()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func external_object_capabilities_remove_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.externalObjectCapabilities.remove()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func external_object_capabilities_remove_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            try await client.v1.externalObjectCapabilities.remove()
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func external_object_capabilities_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.externalObjectCapabilities.create(input: ExternalObjectCapabilityCreateInput(bindings: [:], subject: "test-value"))
        ContractSupport.use(result)
    }

    @Test func external_object_capabilities_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.externalObjectCapabilities.create(input: ExternalObjectCapabilityCreateInput(bindings: [:], subject: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func external_object_capabilities_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.externalObjectCapabilities.create(input: ExternalObjectCapabilityCreateInput(bindings: [:], subject: "test-value"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func external_object_capabilities_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.externalObjectCapabilities.create(input: ExternalObjectCapabilityCreateInput(bindings: [:], subject: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func external_object_capabilities_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.externalObjectCapabilities.create(input: ExternalObjectCapabilityCreateInput(bindings: [:], subject: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func external_object_capabilities_create_error_502() async throws {
        let client = try await ContractSupport.errorClient(502)
        do {
            _ = try await client.v1.externalObjectCapabilities.create(input: ExternalObjectCapabilityCreateInput(bindings: [:], subject: "test-value"))
            Issue.record("Expected ApiError with status 502")
        }
        catch let error as ApiError {
            #expect(error.status == 502)
        }
    }
}
