// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: c97ce384923d

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct ExtractionsContractTests {

    @Test func extractions_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.extractions.create(input: ExtractionCreateInput(destinationKind: "config"))
        ContractSupport.use(result)
    }

    @Test func extractions_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.extractions.create(input: ExtractionCreateInput(destinationKind: "config"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func extractions_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.extractions.create(input: ExtractionCreateInput(destinationKind: "config"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func extractions_create_error_502() async throws {
        let client = try await ContractSupport.errorClient(502)
        do {
            _ = try await client.v1.extractions.create(input: ExtractionCreateInput(destinationKind: "config"))
            Issue.record("Expected ApiError with status 502")
        }
        catch let error as ApiError {
            #expect(error.status == 502)
        }
    }

    @Test func extractions_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.extractions.get(extraction: "test-value")
        ContractSupport.use(result)
    }

    @Test func extractions_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.extractions.get(extraction: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }
}
