// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: e1e3cbe6f677

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct FilesContractTests {

    @Test func files_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.files.create(input: FileCreateInput(contentType: "test-value", data: "test-value", filename: "test-value"))
        ContractSupport.use(result)
    }

    @Test func files_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.files.create(input: FileCreateInput(contentType: "test-value", data: "test-value", filename: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func files_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.files.create(input: FileCreateInput(contentType: "test-value", data: "test-value", filename: "test-value"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func files_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.files.create(input: FileCreateInput(contentType: "test-value", data: "test-value", filename: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func files_avatar_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.files.avatar(file: "test-value", token: "test-token")
        #expect(!result.mimeType.isEmpty)
    }

    @Test func files_avatar_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.files.avatar(file: "test-value", token: "test-token")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }
}
