// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: e402ff84055f

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct KnowledgeIngestionsContractTests {

    @Test func knowledge_ingestions_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.knowledgeIngestions.get(ingestion: "test-value")
        ContractSupport.use(result)
    }

    @Test func knowledge_ingestions_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.knowledgeIngestions.get(ingestion: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func knowledge_ingestions_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.knowledgeIngestions.get(ingestion: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func knowledge_ingestions_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.knowledgeIngestions.get(ingestion: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }
}
