// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 6ceef35eebe2

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct NotificationsContractTests {

    @Test func notifications_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.notifications.list()
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func notifications_list_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.notifications.list()
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func notifications_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.notifications.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func notifications_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.notifications.list()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func notifications_read_all_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.notifications.readAll()
    }

    @Test func notifications_read_all_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.notifications.readAll()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func notifications_read_all_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.notifications.readAll()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func notifications_send_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.notifications.send(input: NotificationSendInput(type: "test", user: "test-value"))
        ContractSupport.use(result)
    }

    @Test func notifications_send_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.notifications.send(input: NotificationSendInput(type: "test", user: "test-value"))
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func notifications_send_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.notifications.send(input: NotificationSendInput(type: "test", user: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func notifications_send_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.notifications.send(input: NotificationSendInput(type: "test", user: "test-value"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func notifications_send_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.notifications.send(input: NotificationSendInput(type: "test", user: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func notifications_send_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.notifications.send(input: NotificationSendInput(type: "test", user: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func notifications_unread_count_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.notifications.unreadCount()
        ContractSupport.use(result)
    }

    @Test func notifications_unread_count_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.notifications.unreadCount()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func notifications_unread_count_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.notifications.unreadCount()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func notifications_archive_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.notifications.archive(notification: "test-value")
    }

    @Test func notifications_archive_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.notifications.archive(notification: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func notifications_archive_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.notifications.archive(notification: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func notifications_archive_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.notifications.archive(notification: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func notifications_read_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.notifications.read(notification: "test-value")
    }

    @Test func notifications_read_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.notifications.read(notification: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func notifications_read_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.notifications.read(notification: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func notifications_read_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.notifications.read(notification: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func notifications_unarchive_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.notifications.unarchive(notification: "test-value")
    }

    @Test func notifications_unarchive_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.notifications.unarchive(notification: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func notifications_unarchive_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.notifications.unarchive(notification: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func notifications_unarchive_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.notifications.unarchive(notification: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }
}
