// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 9ecc73f50cc4

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct OauthContractTests {

    @Test func oauth_scopes_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.oauth.scopes()
        ContractSupport.use(result)
    }

    @Test func oauth_token_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.oauth.token(input: OauthTokenInput(grantType: "test-value"))
        ContractSupport.use(result)
    }

    @Test func oauth_token_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.oauth.token(input: OauthTokenInput(grantType: "test-value"))
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func oauth_token_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.oauth.token(input: OauthTokenInput(grantType: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func oauth_token_error_429() async throws {
        let client = try await ContractSupport.errorClient(429)
        do {
            _ = try await client.v1.oauth.token(input: OauthTokenInput(grantType: "test-value"))
            Issue.record("Expected ApiError with status 429")
        }
        catch let error as ApiError {
            #expect(error.status == 429)
        }
    }

    @Test func oauth_device_approve_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.oauth.device.approve(input: DeviceApproveInput(userCode: "test-value"))
        ContractSupport.use(result)
    }

    @Test func oauth_device_approve_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.oauth.device.approve(input: DeviceApproveInput(userCode: "test-value"))
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func oauth_device_approve_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.oauth.device.approve(input: DeviceApproveInput(userCode: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func oauth_device_authorize_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.oauth.device.authorize(input: DeviceAuthorizeInput(client: "test-value"))
        ContractSupport.use(result)
    }

    @Test func oauth_device_authorize_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.oauth.device.authorize(input: DeviceAuthorizeInput(client: "test-value"))
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func oauth_device_authorize_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.oauth.device.authorize(input: DeviceAuthorizeInput(client: "test-value"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func oauth_device_authorize_error_429() async throws {
        let client = try await ContractSupport.errorClient(429)
        do {
            _ = try await client.v1.oauth.device.authorize(input: DeviceAuthorizeInput(client: "test-value"))
            Issue.record("Expected ApiError with status 429")
        }
        catch let error as ApiError {
            #expect(error.status == 429)
        }
    }

    @Test func oauth_device_deny_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.oauth.device.deny(input: DeviceDenyInput(userCode: "test-value"))
        ContractSupport.use(result)
    }

    @Test func oauth_device_deny_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.oauth.device.deny(input: DeviceDenyInput(userCode: "test-value"))
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func oauth_device_deny_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.oauth.device.deny(input: DeviceDenyInput(userCode: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }
}
