// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 41d961caeb67

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct OrgsContractTests {

    @Test func orgs_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.orgs.list()
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func orgs_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.orgs.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func orgs_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.orgs.list()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func orgs_artifacts_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.orgs.artifacts(org: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func orgs_artifacts_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.orgs.artifacts(org: "test-value")
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func orgs_artifacts_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.orgs.artifacts(org: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func orgs_artifacts_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.orgs.artifacts(org: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func orgs_artifacts_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.orgs.artifacts(org: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func orgs_linked_accounts_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.orgs.linkedAccounts(org: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func orgs_linked_accounts_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.orgs.linkedAccounts(org: "test-value")
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func orgs_linked_accounts_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.orgs.linkedAccounts(org: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func orgs_linked_accounts_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.orgs.linkedAccounts(org: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func orgs_threads_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.orgs.threads.list(org: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func orgs_threads_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.orgs.threads.list(org: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func orgs_threads_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.orgs.threads.list(org: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func orgs_threads_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.orgs.threads.create(org: "test-value", input: OrgThreadCreateInput(thread: OrgThreadCreateInputThread()))
        ContractSupport.use(result)
    }

    @Test func orgs_threads_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.orgs.threads.create(org: "test-value", input: OrgThreadCreateInput(thread: OrgThreadCreateInputThread()))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func orgs_threads_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.orgs.threads.create(org: "test-value", input: OrgThreadCreateInput(thread: OrgThreadCreateInputThread()))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func orgs_threads_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.orgs.threads.create(org: "test-value", input: OrgThreadCreateInput(thread: OrgThreadCreateInputThread()))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func orgs_threads_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.orgs.threads.create(org: "test-value", input: OrgThreadCreateInput(thread: OrgThreadCreateInputThread()))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }
}
