// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 6da605f6a08a

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct PrivateServicesContractTests {

    @Test func private_services_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.privateServices.list()
        ContractSupport.use(result)
    }

    @Test func private_services_list_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.privateServices.list()
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func private_services_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.privateServices.list()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func private_services_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.privateServices.list()
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func private_services_list_error_503() async throws {
        let client = try await ContractSupport.errorClient(503)
        do {
            _ = try await client.v1.privateServices.list()
            Issue.record("Expected ApiError with status 503")
        }
        catch let error as ApiError {
            #expect(error.status == 503)
        }
    }

    @Test func private_services_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.privateServices.create(input: PrivateServiceCreateInput(functions: [PrivateServiceCreateInputFunctionsItem(description: "test description", inputSchema: [:], name: "test-name")]))
        ContractSupport.use(result)
    }

    @Test func private_services_create_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.privateServices.create(input: PrivateServiceCreateInput(functions: [PrivateServiceCreateInputFunctionsItem(description: "test description", inputSchema: [:], name: "test-name")]))
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func private_services_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.privateServices.create(input: PrivateServiceCreateInput(functions: [PrivateServiceCreateInputFunctionsItem(description: "test description", inputSchema: [:], name: "test-name")]))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func private_services_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.privateServices.create(input: PrivateServiceCreateInput(functions: [PrivateServiceCreateInputFunctionsItem(description: "test description", inputSchema: [:], name: "test-name")]))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func private_services_create_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.privateServices.create(input: PrivateServiceCreateInput(functions: [PrivateServiceCreateInputFunctionsItem(description: "test description", inputSchema: [:], name: "test-name")]))
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func private_services_create_error_503() async throws {
        let client = try await ContractSupport.errorClient(503)
        do {
            _ = try await client.v1.privateServices.create(input: PrivateServiceCreateInput(functions: [PrivateServiceCreateInputFunctionsItem(description: "test description", inputSchema: [:], name: "test-name")]))
            Issue.record("Expected ApiError with status 503")
        }
        catch let error as ApiError {
            #expect(error.status == 503)
        }
    }

    @Test func private_services_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.privateServices.get(privateServiceId: "test-id")
        ContractSupport.use(result)
    }

    @Test func private_services_get_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.privateServices.get(privateServiceId: "test-id")
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func private_services_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.privateServices.get(privateServiceId: "test-id")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func private_services_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.privateServices.get(privateServiceId: "test-id")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func private_services_get_error_503() async throws {
        let client = try await ContractSupport.errorClient(503)
        do {
            _ = try await client.v1.privateServices.get(privateServiceId: "test-id")
            Issue.record("Expected ApiError with status 503")
        }
        catch let error as ApiError {
            #expect(error.status == 503)
        }
    }
}
