// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: da6d9d969e92

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct SandboxesContractTests {

    @Test func sandboxes_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.sandboxes.create(input: SandboxCreateInput(name: "test-name", slug: "test-value"))
        ContractSupport.use(result)
    }

    @Test func sandboxes_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.sandboxes.create(input: SandboxCreateInput(name: "test-name", slug: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func sandboxes_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.sandboxes.create(input: SandboxCreateInput(name: "test-name", slug: "test-value"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func sandboxes_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.sandboxes.create(input: SandboxCreateInput(name: "test-name", slug: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func sandboxes_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.sandboxes.create(input: SandboxCreateInput(name: "test-name", slug: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func sandboxes_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.sandboxes.delete(sandbox: "test-value")
    }

    @Test func sandboxes_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.sandboxes.delete(sandbox: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func sandboxes_delete_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.sandboxes.delete(sandbox: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func sandboxes_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.sandboxes.delete(sandbox: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func sandboxes_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.sandboxes.get(sandbox: "test-value")
        ContractSupport.use(result)
    }

    @Test func sandboxes_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.sandboxes.get(sandbox: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func sandboxes_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.sandboxes.get(sandbox: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func sandboxes_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.sandboxes.get(sandbox: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func sandboxes_keys_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.sandboxes.keys(sandbox: "test-value", input: SandboxKeysInput())
        ContractSupport.use(result)
    }

    @Test func sandboxes_keys_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.sandboxes.keys(sandbox: "test-value", input: SandboxKeysInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func sandboxes_keys_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.sandboxes.keys(sandbox: "test-value", input: SandboxKeysInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func sandboxes_keys_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.sandboxes.keys(sandbox: "test-value", input: SandboxKeysInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func sandboxes_keys_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.sandboxes.keys(sandbox: "test-value", input: SandboxKeysInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }
}
