// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: f4ce84a46fb3

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct ScriptsContractTests {

    @Test func scripts_language_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.scripts.language()
        ContractSupport.use(result)
    }

    @Test func scripts_language_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.scripts.language()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func scripts_llm_txt_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.scripts.llmTxt()
        #expect(!result.mimeType.isEmpty)
    }

    @Test func scripts_llm_txt_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.scripts.llmTxt()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func scripts_run_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.scripts.run(input: ScriptRunInput())
        ContractSupport.use(result)
    }

    @Test func scripts_run_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.scripts.run(input: ScriptRunInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func scripts_run_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.scripts.run(input: ScriptRunInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func scripts_run_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.scripts.run(input: ScriptRunInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func scripts_run_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.scripts.run(input: ScriptRunInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func scripts_runtime_env_vars_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.scripts.runtimeEnvVars()
        ContractSupport.use(result)
    }

    @Test func scripts_runtime_env_vars_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.scripts.runtimeEnvVars()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func scripts_runtime_env_vars_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.scripts.runtimeEnvVars()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func scripts_test_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.scripts.test(input: ScriptTestInput())
        ContractSupport.use(result)
    }

    @Test func scripts_test_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.scripts.test(input: ScriptTestInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func scripts_test_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.scripts.test(input: ScriptTestInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func scripts_validate_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.scripts.validate(input: ScriptValidateInput())
        ContractSupport.use(result)
    }

    @Test func scripts_validate_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.scripts.validate(input: ScriptValidateInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }
}
