// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: c30ad2047f05

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct SolutionInstancesContractTests {

    @Test func solution_instances_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.solutionInstances.list(solutionTemplateConfigId: "test-id")
        ContractSupport.use(result)
    }

    @Test func solution_instances_list_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.solutionInstances.list(solutionTemplateConfigId: "test-id")
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func solution_instances_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.solutionInstances.list(solutionTemplateConfigId: "test-id")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func solution_instances_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.solutionInstances.list(solutionTemplateConfigId: "test-id")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }
}
