// Copyright (c) 2026 ArchAstro Inc. All Rights Reserved.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 660644fb8ea6

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct SolutionTagsContractTests {

    @Test func solution_tags_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.solutionTags.list()
        ContractSupport.use(result)
    }

    @Test func solution_tags_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.solutionTags.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func solution_tags_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.solutionTags.list()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }
}
