// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: d57e091eb6d9

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct SshKeysContractTests {

    @Test func ssh_keys_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.sshKeys.delete(sshKey: "test-key")
    }

    @Test func ssh_keys_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.sshKeys.delete(sshKey: "test-key")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func ssh_keys_delete_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.sshKeys.delete(sshKey: "test-key")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func ssh_keys_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.sshKeys.delete(sshKey: "test-key")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }
}
