// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 4cdd8e7e0e7a

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct StatusContractTests {

    @Test func status_ping_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.status.ping()
        ContractSupport.use(result)
    }
}
