// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 2386a5628719

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct TasksContractTests {

    @Test func tasks_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.tasks.delete(task: "test-value")
    }

    @Test func tasks_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.tasks.delete(task: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.tasks.delete(task: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_delete_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            try await client.v1.tasks.delete(task: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.tasks.get(task: "test-value")
        ContractSupport.use(result)
    }

    @Test func tasks_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.tasks.get(task: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.tasks.get(task: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_get_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.tasks.get(task: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_replace_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.tasks.replace(task: "test-value", input: TaskReplaceInput())
        ContractSupport.use(result)
    }

    @Test func tasks_replace_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.tasks.replace(task: "test-value", input: TaskReplaceInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_replace_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.tasks.replace(task: "test-value", input: TaskReplaceInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func tasks_replace_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.tasks.replace(task: "test-value", input: TaskReplaceInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_replace_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.tasks.replace(task: "test-value", input: TaskReplaceInput())
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func tasks_replace_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.tasks.replace(task: "test-value", input: TaskReplaceInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_activity_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.tasks.activity(task: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func tasks_activity_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.tasks.activity(task: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_activity_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.tasks.activity(task: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_activity_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.tasks.activity(task: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_blocking_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.tasks.blocking(task: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func tasks_blocking_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.tasks.blocking(task: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_blocking_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.tasks.blocking(task: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_blocking_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.tasks.blocking(task: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_subtasks_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.tasks.subtasks(task: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func tasks_subtasks_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.tasks.subtasks(task: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_subtasks_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.tasks.subtasks(task: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_subtasks_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.tasks.subtasks(task: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_blockers_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.tasks.blockers.list(task: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func tasks_blockers_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.tasks.blockers.list(task: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_blockers_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.tasks.blockers.list(task: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_blockers_list_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.tasks.blockers.list(task: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_blockers_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.tasks.blockers.create(task: "test-value", input: BlockerCreateInput(blocker: "test-value"))
        ContractSupport.use(result)
    }

    @Test func tasks_blockers_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.tasks.blockers.create(task: "test-value", input: BlockerCreateInput(blocker: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_blockers_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.tasks.blockers.create(task: "test-value", input: BlockerCreateInput(blocker: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_blockers_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.tasks.blockers.create(task: "test-value", input: BlockerCreateInput(blocker: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_blockers_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.tasks.blockers.delete(task: "test-value", blocker: "test-value")
    }

    @Test func tasks_blockers_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.tasks.blockers.delete(task: "test-value", blocker: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_blockers_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.tasks.blockers.delete(task: "test-value", blocker: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_blockers_delete_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            try await client.v1.tasks.blockers.delete(task: "test-value", blocker: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_comments_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.tasks.comments.list(task: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func tasks_comments_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.tasks.comments.list(task: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_comments_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.tasks.comments.list(task: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_comments_list_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.tasks.comments.list(task: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_comments_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.tasks.comments.create(task: "test-value", input: CommentCreateInput(comment: CommentCreateInputComment(body: "test-value")))
        ContractSupport.use(result)
    }

    @Test func tasks_comments_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.tasks.comments.create(task: "test-value", input: CommentCreateInput(comment: CommentCreateInputComment(body: "test-value")))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_comments_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.tasks.comments.create(task: "test-value", input: CommentCreateInput(comment: CommentCreateInputComment(body: "test-value")))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_comments_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.tasks.comments.create(task: "test-value", input: CommentCreateInput(comment: CommentCreateInputComment(body: "test-value")))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_comments_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.tasks.comments.delete(task: "test-value", comment: "test-value")
    }

    @Test func tasks_comments_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.tasks.comments.delete(task: "test-value", comment: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_comments_delete_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.tasks.comments.delete(task: "test-value", comment: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func tasks_comments_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.tasks.comments.delete(task: "test-value", comment: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_comments_delete_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            try await client.v1.tasks.comments.delete(task: "test-value", comment: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_comments_replace_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.tasks.comments.replace(task: "test-value", comment: "test-value", input: CommentReplaceInput(body: "test-value"))
        ContractSupport.use(result)
    }

    @Test func tasks_comments_replace_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.tasks.comments.replace(task: "test-value", comment: "test-value", input: CommentReplaceInput(body: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_comments_replace_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.tasks.comments.replace(task: "test-value", comment: "test-value", input: CommentReplaceInput(body: "test-value"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func tasks_comments_replace_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.tasks.comments.replace(task: "test-value", comment: "test-value", input: CommentReplaceInput(body: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_comments_replace_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.tasks.comments.replace(task: "test-value", comment: "test-value", input: CommentReplaceInput(body: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_lease_remove_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.tasks.lease.remove(task: "test-value")
    }

    @Test func tasks_lease_remove_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.tasks.lease.remove(task: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_lease_remove_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.tasks.lease.remove(task: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func tasks_lease_remove_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.tasks.lease.remove(task: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_lease_remove_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            try await client.v1.tasks.lease.remove(task: "test-value")
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func tasks_lease_remove_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            try await client.v1.tasks.lease.remove(task: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_lease_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.tasks.lease.list(task: "test-value")
        ContractSupport.use(result)
    }

    @Test func tasks_lease_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.tasks.lease.list(task: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_lease_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.tasks.lease.list(task: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func tasks_lease_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.tasks.lease.list(task: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_lease_list_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.tasks.lease.list(task: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_lease_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.tasks.lease.create(task: "test-value", input: LeaseCreateInput(harness: "test-value", leaseId: "test-id", sessionId: "test-id", sessionName: "test-value"))
        ContractSupport.use(result)
    }

    @Test func tasks_lease_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.tasks.lease.create(task: "test-value", input: LeaseCreateInput(harness: "test-value", leaseId: "test-id", sessionId: "test-id", sessionName: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_lease_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.tasks.lease.create(task: "test-value", input: LeaseCreateInput(harness: "test-value", leaseId: "test-id", sessionId: "test-id", sessionName: "test-value"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func tasks_lease_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.tasks.lease.create(task: "test-value", input: LeaseCreateInput(harness: "test-value", leaseId: "test-id", sessionId: "test-id", sessionName: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_lease_create_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.tasks.lease.create(task: "test-value", input: LeaseCreateInput(harness: "test-value", leaseId: "test-id", sessionId: "test-id", sessionName: "test-value"))
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func tasks_lease_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.tasks.lease.create(task: "test-value", input: LeaseCreateInput(harness: "test-value", leaseId: "test-id", sessionId: "test-id", sessionName: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_lease_renew_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.tasks.lease.renew(task: "test-value", input: LeaseRenewInput(leaseId: "test-id", sessionId: "test-id"))
        ContractSupport.use(result)
    }

    @Test func tasks_lease_renew_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.tasks.lease.renew(task: "test-value", input: LeaseRenewInput(leaseId: "test-id", sessionId: "test-id"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_lease_renew_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.tasks.lease.renew(task: "test-value", input: LeaseRenewInput(leaseId: "test-id", sessionId: "test-id"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func tasks_lease_renew_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.tasks.lease.renew(task: "test-value", input: LeaseRenewInput(leaseId: "test-id", sessionId: "test-id"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_lease_renew_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.tasks.lease.renew(task: "test-value", input: LeaseRenewInput(leaseId: "test-id", sessionId: "test-id"))
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func tasks_lease_renew_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.tasks.lease.renew(task: "test-value", input: LeaseRenewInput(leaseId: "test-id", sessionId: "test-id"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_links_remove_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.tasks.links.remove(task: "test-value")
    }

    @Test func tasks_links_remove_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.tasks.links.remove(task: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_links_remove_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.tasks.links.remove(task: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_links_remove_error_502() async throws {
        let client = try await ContractSupport.errorClient(502)
        do {
            try await client.v1.tasks.links.remove(task: "test-value")
            Issue.record("Expected ApiError with status 502")
        }
        catch let error as ApiError {
            #expect(error.status == 502)
        }
    }

    @Test func tasks_links_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.tasks.links.create(task: "test-value", input: LinkCreateInput(externalScope: "test-value", objectId: "test-id", objectType: "test-value"))
        #expect(result != JSONValue.null)
    }

    @Test func tasks_links_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.tasks.links.create(task: "test-value", input: LinkCreateInput(externalScope: "test-value", objectId: "test-id", objectType: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func tasks_links_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.tasks.links.create(task: "test-value", input: LinkCreateInput(externalScope: "test-value", objectId: "test-id", objectType: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func tasks_links_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.tasks.links.create(task: "test-value", input: LinkCreateInput(externalScope: "test-value", objectId: "test-id", objectType: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func tasks_links_create_error_502() async throws {
        let client = try await ContractSupport.errorClient(502)
        do {
            _ = try await client.v1.tasks.links.create(task: "test-value", input: LinkCreateInput(externalScope: "test-value", objectId: "test-id", objectType: "test-value"))
            Issue.record("Expected ApiError with status 502")
        }
        catch let error as ApiError {
            #expect(error.status == 502)
        }
    }
}
