// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 28dd64bc1b67

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct TeamMembershipsContractTests {

    @Test func team_memberships_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.teamMemberships.list()
        ContractSupport.use(result)
    }

    @Test func team_memberships_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.teamMemberships.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func team_memberships_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.teamMemberships.list()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func team_memberships_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.teamMemberships.delete(teamMembership: "test-value")
    }

    @Test func team_memberships_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.teamMemberships.delete(teamMembership: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func team_memberships_delete_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.teamMemberships.delete(teamMembership: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func team_memberships_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.teamMemberships.delete(teamMembership: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func team_memberships_delete_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            try await client.v1.teamMemberships.delete(teamMembership: "test-value")
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }
}
