// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 69264a393c07

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct ThreadsContractTests {

    @Test func threads_delete_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.threads.delete(thread: "test-value")
    }

    @Test func threads_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.threads.delete(thread: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_delete_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.threads.delete(thread: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.threads.delete(thread: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.get(thread: "test-value")
        ContractSupport.use(result)
    }

    @Test func threads_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.get(thread: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.get(thread: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.get(thread: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_replace_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.replace(thread: "test-value", input: ThreadReplaceInput())
        ContractSupport.use(result)
    }

    @Test func threads_replace_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.threads.replace(thread: "test-value", input: ThreadReplaceInput())
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func threads_replace_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.replace(thread: "test-value", input: ThreadReplaceInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_replace_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.replace(thread: "test-value", input: ThreadReplaceInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_replace_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.replace(thread: "test-value", input: ThreadReplaceInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_replace_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.threads.replace(thread: "test-value", input: ThreadReplaceInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func threads_agents_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.agents(thread: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func threads_agents_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.agents(thread: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_agents_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.agents(thread: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_agents_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.agents(thread: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_artifacts_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.artifacts(thread: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func threads_artifacts_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.threads.artifacts(thread: "test-value")
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func threads_artifacts_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.artifacts(thread: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_artifacts_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.artifacts(thread: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_artifacts_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.artifacts(thread: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_mark_read_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.threads.markRead(thread: "test-value", input: ThreadMarkReadInput())
    }

    @Test func threads_mark_read_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.threads.markRead(thread: "test-value", input: ThreadMarkReadInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_mark_read_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.threads.markRead(thread: "test-value", input: ThreadMarkReadInput())
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_mark_read_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            try await client.v1.threads.markRead(thread: "test-value", input: ThreadMarkReadInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func threads_messages_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.messages(thread: "test-value")
        ContractSupport.use(result)
    }

    @Test func threads_messages_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.threads.messages(thread: "test-value")
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func threads_messages_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.messages(thread: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_messages_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.messages(thread: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_messages_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.messages(thread: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_picture_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.picture(thread: "test-value", input: ThreadPictureInput(picture: ThreadPictureInputPicture(data: "test-value", filename: "test-value", mimeType: "application/json")))
        ContractSupport.use(result)
    }

    @Test func threads_picture_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.picture(thread: "test-value", input: ThreadPictureInput(picture: ThreadPictureInputPicture(data: "test-value", filename: "test-value", mimeType: "application/json")))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_picture_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.picture(thread: "test-value", input: ThreadPictureInput(picture: ThreadPictureInputPicture(data: "test-value", filename: "test-value", mimeType: "application/json")))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_picture_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.picture(thread: "test-value", input: ThreadPictureInput(picture: ThreadPictureInputPicture(data: "test-value", filename: "test-value", mimeType: "application/json")))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_picture_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.threads.picture(thread: "test-value", input: ThreadPictureInput(picture: ThreadPictureInputPicture(data: "test-value", filename: "test-value", mimeType: "application/json")))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func threads_read_status_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.readStatus(thread: "test-value")
        ContractSupport.use(result)
    }

    @Test func threads_read_status_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.readStatus(thread: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_read_status_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.readStatus(thread: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_read_status_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.readStatus(thread: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_search_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.search(thread: "test-value", q: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func threads_search_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.threads.search(thread: "test-value", q: "test-value")
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func threads_search_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.search(thread: "test-value", q: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_search_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.search(thread: "test-value", q: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_search_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.search(thread: "test-value", q: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_search_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.threads.search(thread: "test-value", q: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func threads_search_error_502() async throws {
        let client = try await ContractSupport.errorClient(502)
        do {
            _ = try await client.v1.threads.search(thread: "test-value", q: "test-value")
            Issue.record("Expected ApiError with status 502")
        }
        catch let error as ApiError {
            #expect(error.status == 502)
        }
    }

    @Test func threads_trajectories_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.trajectories(thread: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func threads_trajectories_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.threads.trajectories(thread: "test-value")
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func threads_trajectories_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.trajectories(thread: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_trajectories_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.trajectories(thread: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_trajectories_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.trajectories(thread: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_members_remove_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.threads.members.remove(thread: "test-value")
    }

    @Test func threads_members_remove_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.threads.members.remove(thread: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_members_remove_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.threads.members.remove(thread: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_members_remove_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.threads.members.remove(thread: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_members_remove_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            try await client.v1.threads.members.remove(thread: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func threads_members_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.members.list(thread: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func threads_members_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.members.list(thread: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_members_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.members.list(thread: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_members_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.members.list(thread: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_members_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.members.create(thread: "test-value", input: ThreadMemberCreateInput(type: "test"))
        ContractSupport.use(result)
    }

    @Test func threads_members_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.members.create(thread: "test-value", input: ThreadMemberCreateInput(type: "test"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_members_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.members.create(thread: "test-value", input: ThreadMemberCreateInput(type: "test"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_members_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.members.create(thread: "test-value", input: ThreadMemberCreateInput(type: "test"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_members_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.threads.members.create(thread: "test-value", input: ThreadMemberCreateInput(type: "test"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func threads_settings_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.settings.list(thread: "test-value")
        ContractSupport.use(result)
    }

    @Test func threads_settings_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.settings.list(thread: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_settings_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.settings.list(thread: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_settings_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.settings.list(thread: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_settings_replace_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.settings.replace(thread: "test-value", input: SettingReplaceInput(settings: [:]))
        ContractSupport.use(result)
    }

    @Test func threads_settings_replace_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.settings.replace(thread: "test-value", input: SettingReplaceInput(settings: [:]))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_settings_replace_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.settings.replace(thread: "test-value", input: SettingReplaceInput(settings: [:]))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_settings_replace_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.settings.replace(thread: "test-value", input: SettingReplaceInput(settings: [:]))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_settings_replace_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.threads.settings.replace(thread: "test-value", input: SettingReplaceInput(settings: [:]))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func threads_tags_remove_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.tags.remove(thread: "test-value")
        ContractSupport.use(result)
    }

    @Test func threads_tags_remove_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.tags.remove(thread: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_tags_remove_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.tags.remove(thread: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_tags_remove_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.tags.remove(thread: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_tags_remove_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.threads.tags.remove(thread: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func threads_tags_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.tags.create(thread: "test-value", input: TagCreateInput(tags: ["test-value"]))
        ContractSupport.use(result)
    }

    @Test func threads_tags_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.tags.create(thread: "test-value", input: TagCreateInput(tags: ["test-value"]))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_tags_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.tags.create(thread: "test-value", input: TagCreateInput(tags: ["test-value"]))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_tags_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.tags.create(thread: "test-value", input: TagCreateInput(tags: ["test-value"]))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_tags_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.threads.tags.create(thread: "test-value", input: TagCreateInput(tags: ["test-value"]))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func threads_tags_replace_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.threads.tags.replace(thread: "test-value", input: TagReplaceInput(tags: ["test-value"]))
        ContractSupport.use(result)
    }

    @Test func threads_tags_replace_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.threads.tags.replace(thread: "test-value", input: TagReplaceInput(tags: ["test-value"]))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func threads_tags_replace_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.threads.tags.replace(thread: "test-value", input: TagReplaceInput(tags: ["test-value"]))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func threads_tags_replace_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.threads.tags.replace(thread: "test-value", input: TagReplaceInput(tags: ["test-value"]))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func threads_tags_replace_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.threads.tags.replace(thread: "test-value", input: TagReplaceInput(tags: ["test-value"]))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }
}
