// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 394257aead36

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct UsersContractTests {

    @Test func users_me_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.me()
        ContractSupport.use(result)
    }

    @Test func users_me_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.users.me()
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func users_me_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.me()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_me_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.me()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.get(user: "test-value")
        ContractSupport.use(result)
    }

    @Test func users_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.get(user: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.get(user: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_artifacts_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.artifacts(user: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func users_artifacts_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.users.artifacts(user: "test-value")
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func users_artifacts_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.artifacts(user: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_artifacts_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.artifacts(user: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_invites_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.invites(user: "test-value", input: UserInvitesInput(invite: UserInvitesInputInvite()))
        ContractSupport.use(result)
    }

    @Test func users_invites_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.invites(user: "test-value", input: UserInvitesInput(invite: UserInvitesInputInvite()))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_invites_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.invites(user: "test-value", input: UserInvitesInput(invite: UserInvitesInputInvite()))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_invites_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.users.invites(user: "test-value", input: UserInvitesInput(invite: UserInvitesInputInvite()))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func users_invites_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.users.invites(user: "test-value", input: UserInvitesInput(invite: UserInvitesInputInvite()))
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func users_invites_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.users.invites(user: "test-value", input: UserInvitesInput(invite: UserInvitesInputInvite()))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func users_orgs_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.orgs(user: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func users_orgs_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.orgs(user: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_profile_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.profile(user: "test-value", input: UserProfileInput())
        ContractSupport.use(result)
    }

    @Test func users_profile_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.profile(user: "test-value", input: UserProfileInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_profile_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.users.profile(user: "test-value", input: UserProfileInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func users_integrations_access_token_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.integrations.accessToken(user: "test-value", provider: "test-id")
        ContractSupport.use(result)
    }

    @Test func users_integrations_access_token_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.integrations.accessToken(user: "test-value", provider: "test-id")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_integrations_access_token_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.integrations.accessToken(user: "test-value", provider: "test-id")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_integrations_access_token_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.users.integrations.accessToken(user: "test-value", provider: "test-id")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func users_integrations_access_token_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.users.integrations.accessToken(user: "test-value", provider: "test-id")
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func users_integrations_access_token_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.users.integrations.accessToken(user: "test-value", provider: "test-id")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func users_integrations_access_token_error_502() async throws {
        let client = try await ContractSupport.errorClient(502)
        do {
            _ = try await client.v1.users.integrations.accessToken(user: "test-value", provider: "test-id")
            Issue.record("Expected ApiError with status 502")
        }
        catch let error as ApiError {
            #expect(error.status == 502)
        }
    }

    @Test func users_ssh_keys_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.sshKeys.list(user: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func users_ssh_keys_list_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.users.sshKeys.list(user: "test-value")
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func users_ssh_keys_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.sshKeys.list(user: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_ssh_keys_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.sshKeys.list(user: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_ssh_keys_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.sshKeys.create(user: "test-value", input: UserSshKeyCreateInput(label: "test-value", publicKey: "test-key"))
        ContractSupport.use(result)
    }

    @Test func users_ssh_keys_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.sshKeys.create(user: "test-value", input: UserSshKeyCreateInput(label: "test-value", publicKey: "test-key"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_ssh_keys_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.sshKeys.create(user: "test-value", input: UserSshKeyCreateInput(label: "test-value", publicKey: "test-key"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_ssh_keys_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.users.sshKeys.create(user: "test-value", input: UserSshKeyCreateInput(label: "test-value", publicKey: "test-key"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func users_tasks_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.tasks.list(user: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func users_tasks_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.tasks.list(user: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_tasks_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.users.tasks.list(user: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func users_tasks_list_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.users.tasks.list(user: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func users_tasks_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.tasks.create(user: "test-value", input: UserTaskCreateInput(task: UserTaskCreateInputTask(name: "test-name")))
        ContractSupport.use(result)
    }

    @Test func users_tasks_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.tasks.create(user: "test-value", input: UserTaskCreateInput(task: UserTaskCreateInputTask(name: "test-name")))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_tasks_create_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.users.tasks.create(user: "test-value", input: UserTaskCreateInput(task: UserTaskCreateInputTask(name: "test-name")))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func users_tasks_create_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.users.tasks.create(user: "test-value", input: UserTaskCreateInput(task: UserTaskCreateInputTask(name: "test-name")))
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func users_tasks_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.users.tasks.create(user: "test-value", input: UserTaskCreateInput(task: UserTaskCreateInputTask(name: "test-name")))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func users_tasks_blocker_cycles_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.tasks.blockerCycles(user: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func users_tasks_blocker_cycles_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.tasks.blockerCycles(user: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_tasks_blocker_cycles_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.users.tasks.blockerCycles(user: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func users_tasks_blocker_cycles_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.users.tasks.blockerCycles(user: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func users_tasks_ready_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.tasks.ready(user: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func users_tasks_ready_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.tasks.ready(user: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_tasks_ready_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.users.tasks.ready(user: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func users_tasks_ready_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.users.tasks.ready(user: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func users_tasks_search_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.tasks.search(user: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func users_tasks_search_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.tasks.search(user: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_tasks_search_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.users.tasks.search(user: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func users_tasks_search_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.users.tasks.search(user: "test-value")
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func users_threads_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.threads.list(user: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func users_threads_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.threads.list(user: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_threads_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.threads.list(user: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_threads_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.threads.create(user: "test-value", input: UserThreadCreateInput(thread: UserThreadCreateInputThread()))
        ContractSupport.use(result)
    }

    @Test func users_threads_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.threads.create(user: "test-value", input: UserThreadCreateInput(thread: UserThreadCreateInputThread()))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_threads_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.threads.create(user: "test-value", input: UserThreadCreateInput(thread: UserThreadCreateInputThread()))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_threads_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.users.threads.create(user: "test-value", input: UserThreadCreateInput(thread: UserThreadCreateInputThread()))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func users_tokens_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.tokens.list(user: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func users_tokens_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.tokens.list(user: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_tokens_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.tokens.list(user: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_tokens_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.tokens.create(user: "test-value", input: TokenCreateInput())
        ContractSupport.use(result)
    }

    @Test func users_tokens_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.tokens.create(user: "test-value", input: TokenCreateInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_tokens_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.tokens.create(user: "test-value", input: TokenCreateInput())
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_tokens_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.users.tokens.create(user: "test-value", input: TokenCreateInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func users_tokens_create_error_429() async throws {
        let client = try await ContractSupport.errorClient(429)
        do {
            _ = try await client.v1.users.tokens.create(user: "test-value", input: TokenCreateInput())
            Issue.record("Expected ApiError with status 429")
        }
        catch let error as ApiError {
            #expect(error.status == 429)
        }
    }

    @Test func users_tokens_delete_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.tokens.delete(user: "test-value", token: "test-token")
        ContractSupport.use(result)
    }

    @Test func users_tokens_delete_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.tokens.delete(user: "test-value", token: "test-token")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_tokens_delete_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.tokens.delete(user: "test-value", token: "test-token")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_tokens_delete_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.users.tokens.delete(user: "test-value", token: "test-token")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }
}
