// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: a6dc02010a31

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct UsersContractTests {

    @Test func users_me_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.me()
        ContractSupport.use(result)
    }

    @Test func users_me_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.me()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.get(user: "test-value")
        ContractSupport.use(result)
    }

    @Test func users_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.get(user: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_get_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.get(user: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_artifacts_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.artifacts(user: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func users_artifacts_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.artifacts(user: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_artifacts_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.artifacts(user: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_invites_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.invites(user: "test-value", input: UserInvitesInput(invite: UserInvitesInputInvite()))
        ContractSupport.use(result)
    }

    @Test func users_invites_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.invites(user: "test-value", input: UserInvitesInput(invite: UserInvitesInputInvite()))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_invites_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.invites(user: "test-value", input: UserInvitesInput(invite: UserInvitesInputInvite()))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_invites_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.users.invites(user: "test-value", input: UserInvitesInput(invite: UserInvitesInputInvite()))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func users_invites_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            _ = try await client.v1.users.invites(user: "test-value", input: UserInvitesInput(invite: UserInvitesInputInvite()))
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func users_invites_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.users.invites(user: "test-value", input: UserInvitesInput(invite: UserInvitesInputInvite()))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func users_orgs_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.orgs(user: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func users_orgs_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.orgs(user: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_profile_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.profile(user: "test-value", input: UserProfileInput())
        ContractSupport.use(result)
    }

    @Test func users_profile_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.profile(user: "test-value", input: UserProfileInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_profile_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.users.profile(user: "test-value", input: UserProfileInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func users_threads_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.threads.list(user: "test-value")
        ContractSupport.use(result.data)
        ContractSupport.use(result)
    }

    @Test func users_threads_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.threads.list(user: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_threads_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.threads.list(user: "test-value")
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_threads_create_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.users.threads.create(user: "test-value", input: UserThreadCreateInput(thread: UserThreadCreateInputThread()))
        ContractSupport.use(result)
    }

    @Test func users_threads_create_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.users.threads.create(user: "test-value", input: UserThreadCreateInput(thread: UserThreadCreateInputThread()))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func users_threads_create_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.users.threads.create(user: "test-value", input: UserThreadCreateInput(thread: UserThreadCreateInputThread()))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func users_threads_create_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.users.threads.create(user: "test-value", input: UserThreadCreateInput(thread: UserThreadCreateInputThread()))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }
}
