// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 715f3ce2a608

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct WorkflowsContractTests {

    @Test func workflows_commands_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.workflows.commands()
        #expect(result.count >= 0)
    }

    @Test func workflows_commands_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.workflows.commands()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func workflows_llm_txt_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.workflows.llmTxt()
        #expect(!result.mimeType.isEmpty)
    }

    @Test func workflows_llm_txt_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.workflows.llmTxt()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func workflows_run_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.workflows.run(input: WorkflowRunInput())
        ContractSupport.use(result)
    }

    @Test func workflows_run_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.workflows.run(input: WorkflowRunInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func workflows_run_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.workflows.run(input: WorkflowRunInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func workflows_events_sample_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.workflows.events.sample(name: "test-name")
        ContractSupport.use(result)
    }

    @Test func workflows_events_sample_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.workflows.events.sample(name: "test-name")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func workflows_events_sample_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.workflows.events.sample(name: "test-name")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func workflows_expressions_run_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.workflows.expressions.run(input: ExpressionRunInput())
        ContractSupport.use(result)
    }

    @Test func workflows_expressions_run_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.workflows.expressions.run(input: ExpressionRunInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func workflows_expressions_run_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.workflows.expressions.run(input: ExpressionRunInput())
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func workflows_expressions_validate_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.workflows.expressions.validate(input: ExpressionValidateInput())
        ContractSupport.use(result)
    }

    @Test func workflows_expressions_validate_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.workflows.expressions.validate(input: ExpressionValidateInput())
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func workflows_graph_validate_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.workflows.graph.validate(input: GraphValidateInput(graph: [:]))
        ContractSupport.use(result)
    }

    @Test func workflows_graph_validate_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.workflows.graph.validate(input: GraphValidateInput(graph: [:]))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func workflows_node_types_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.workflows.nodeTypes.list()
        #expect(result.count >= 0)
    }

    @Test func workflows_node_types_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.workflows.nodeTypes.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func workflows_node_types_get_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.workflows.nodeTypes.get(nodeType: "test-value")
        ContractSupport.use(result)
    }

    @Test func workflows_node_types_get_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.workflows.nodeTypes.get(nodeType: "test-value")
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func workflows_node_types_get_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.workflows.nodeTypes.get(nodeType: "test-value")
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func workflows_sample_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.workflows.sample.list()
        #expect(!result.mimeType.isEmpty)
    }

    @Test func workflows_sample_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.workflows.sample.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }
}
