// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: cbc409179bb7

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized) struct WorkItemsContractTests {

    @Test func work_items_list_success() async throws {
        let client = try await ContractSupport.client()
        let result = try await client.v1.workItems.list()
        ContractSupport.use(result)
    }

    @Test func work_items_list_error_400() async throws {
        let client = try await ContractSupport.errorClient(400)
        do {
            _ = try await client.v1.workItems.list()
            Issue.record("Expected ApiError with status 400")
        }
        catch let error as ApiError {
            #expect(error.status == 400)
        }
    }

    @Test func work_items_list_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            _ = try await client.v1.workItems.list()
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func work_items_list_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            _ = try await client.v1.workItems.list()
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func work_items_list_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            _ = try await client.v1.workItems.list()
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func work_items_list_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            _ = try await client.v1.workItems.list()
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func work_items_fail_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.workItems.fail(workItem: "test-value", input: WorkItemFailInput(error: [:], leaseOwner: "test-value"))
    }

    @Test func work_items_fail_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.workItems.fail(workItem: "test-value", input: WorkItemFailInput(error: [:], leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func work_items_fail_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.workItems.fail(workItem: "test-value", input: WorkItemFailInput(error: [:], leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func work_items_fail_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.workItems.fail(workItem: "test-value", input: WorkItemFailInput(error: [:], leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func work_items_fail_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            try await client.v1.workItems.fail(workItem: "test-value", input: WorkItemFailInput(error: [:], leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func work_items_fail_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            try await client.v1.workItems.fail(workItem: "test-value", input: WorkItemFailInput(error: [:], leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func work_items_heartbeat_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.workItems.heartbeat(workItem: "test-value", input: WorkItemHeartbeatInput(leaseOwner: "test-value"))
    }

    @Test func work_items_heartbeat_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.workItems.heartbeat(workItem: "test-value", input: WorkItemHeartbeatInput(leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func work_items_heartbeat_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.workItems.heartbeat(workItem: "test-value", input: WorkItemHeartbeatInput(leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func work_items_heartbeat_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.workItems.heartbeat(workItem: "test-value", input: WorkItemHeartbeatInput(leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func work_items_heartbeat_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            try await client.v1.workItems.heartbeat(workItem: "test-value", input: WorkItemHeartbeatInput(leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func work_items_heartbeat_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            try await client.v1.workItems.heartbeat(workItem: "test-value", input: WorkItemHeartbeatInput(leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func work_items_start_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.workItems.start(workItem: "test-value", input: WorkItemStartInput(leaseOwner: "test-value"))
    }

    @Test func work_items_start_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.workItems.start(workItem: "test-value", input: WorkItemStartInput(leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func work_items_start_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.workItems.start(workItem: "test-value", input: WorkItemStartInput(leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func work_items_start_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.workItems.start(workItem: "test-value", input: WorkItemStartInput(leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func work_items_start_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            try await client.v1.workItems.start(workItem: "test-value", input: WorkItemStartInput(leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func work_items_start_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            try await client.v1.workItems.start(workItem: "test-value", input: WorkItemStartInput(leaseOwner: "test-value"))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }

    @Test func work_items_submit_success() async throws {
        let client = try await ContractSupport.client()
        try await client.v1.workItems.submit(workItem: "test-value", input: WorkItemSubmitInput(leaseOwner: "test-value", result: [:]))
    }

    @Test func work_items_submit_error_401() async throws {
        let client = try await ContractSupport.errorClient(401)
        do {
            try await client.v1.workItems.submit(workItem: "test-value", input: WorkItemSubmitInput(leaseOwner: "test-value", result: [:]))
            Issue.record("Expected ApiError with status 401")
        }
        catch let error as ApiError {
            #expect(error.status == 401)
        }
    }

    @Test func work_items_submit_error_403() async throws {
        let client = try await ContractSupport.errorClient(403)
        do {
            try await client.v1.workItems.submit(workItem: "test-value", input: WorkItemSubmitInput(leaseOwner: "test-value", result: [:]))
            Issue.record("Expected ApiError with status 403")
        }
        catch let error as ApiError {
            #expect(error.status == 403)
        }
    }

    @Test func work_items_submit_error_404() async throws {
        let client = try await ContractSupport.errorClient(404)
        do {
            try await client.v1.workItems.submit(workItem: "test-value", input: WorkItemSubmitInput(leaseOwner: "test-value", result: [:]))
            Issue.record("Expected ApiError with status 404")
        }
        catch let error as ApiError {
            #expect(error.status == 404)
        }
    }

    @Test func work_items_submit_error_409() async throws {
        let client = try await ContractSupport.errorClient(409)
        do {
            try await client.v1.workItems.submit(workItem: "test-value", input: WorkItemSubmitInput(leaseOwner: "test-value", result: [:]))
            Issue.record("Expected ApiError with status 409")
        }
        catch let error as ApiError {
            #expect(error.status == 409)
        }
    }

    @Test func work_items_submit_error_422() async throws {
        let client = try await ContractSupport.errorClient(422)
        do {
            try await client.v1.workItems.submit(workItem: "test-value", input: WorkItemSubmitInput(leaseOwner: "test-value", result: [:]))
            Issue.record("Expected ApiError with status 422")
        }
        catch let error as ApiError {
            #expect(error.status == 422)
        }
    }
}
