// Copyright (c) 2026 ArchAstro Inc. Licensed under the MIT License.
// This file is auto-generated by @archastro/sdk-generator. Do not edit.
// Content hash: 6096b0d28d5b

import Foundation
import Testing
import ArchAstroPlatform

@Suite(.serialized, .enabled(if: ContractSupport.channelTestsEnabled)) struct AiStreamContractTests {

    @Test func ai_chat_completions_stream_yields_sse_events() async throws {
        try await ContractSupport.withHarness { harness in
            try await harness.registerStreamScenario([
                "route": "POST /api/v1/ai/chat/completions/stream",
                "actions": [["type": "autoEmit", "event": "done"], ["type": "autoEmit", "event": "error"], ["type": "autoEmit", "event": "message_complete"], ["type": "autoEmit", "event": "message_delta"], ["type": "autoEmit", "event": "tool_call_delta"], ["type": "autoEmit", "event": "tool_result"]],
            ])
            let client = PlatformClient(
                baseUrl: harness.controlURL,
                accessToken: "test-token",
                defaultHeaders: ["x-archastro-api-key": "pk_test-key"]
            )
            var events: [String] = []
            for try await event in client.v1.ai.chat.completions.stream(input: CompletionStreamInput(messages: [CompletionStreamInputMessagesItem(role: "user")], opts: CompletionStreamInputOpts(model: "test-model"))) {
                events.append(event.event)
            }
            #expect(events == ["done", "error", "message_complete", "message_delta", "tool_call_delta", "tool_result"])
        }
    }

    @Test func ai_chat_completions_stream_rejects_non_2xx() async throws {
        try await ContractSupport.withHarness { harness in
            try await harness.registerStreamScenario([
                "route": "POST /api/v1/ai/chat/completions/stream",
                "actions": [["type": "status", "code": 402, "body": ["error": ["code": "plan_not_entitled"]]]],
            ])
            let client = PlatformClient(
                baseUrl: harness.controlURL,
                accessToken: "test-token",
                defaultHeaders: ["x-archastro-api-key": "pk_test-key"]
            )
            await #expect(throws: ApiError.self) {
                for try await _ in client.v1.ai.chat.completions.stream(input: CompletionStreamInput(messages: [CompletionStreamInputMessagesItem(role: "user")], opts: CompletionStreamInputOpts(model: "test-model"))) {}
            }
        }
    }
}
